// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_core::imp::define_interface!(
    AttestationChallengeHandler,
    AttestationChallengeHandler_Vtbl,
    0xf6ae35b0_d805_587d_944f_a09bd032acf5
);
impl windows_core::RuntimeType for AttestationChallengeHandler {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl AttestationChallengeHandler {
    pub fn new<
        F: Fn(windows_core::Ref<IBuffer>) -> windows_core::Result<IBuffer> + Send + 'static,
    >(
        invoke: F,
    ) -> Self {
        let com = AttestationChallengeHandlerBox {
            vtable: &AttestationChallengeHandlerBox::<F>::VTABLE,
            count: windows_core::imp::RefCount::new(1),
            invoke,
        };
        unsafe { core::mem::transmute(windows_core::imp::Box::new(com)) }
    }
    pub fn Invoke<P0>(&self, challenge: P0) -> windows_core::Result<IBuffer>
    where
        P0: windows_core::Param<IBuffer>,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Invoke)(
                windows_core::Interface::as_raw(this),
                challenge.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct AttestationChallengeHandler_Vtbl {
    base__: windows_core::IUnknown_Vtbl,
    Invoke: unsafe extern "system" fn(
        this: *mut core::ffi::c_void,
        challenge: *mut core::ffi::c_void,
        result__: *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
#[repr(C)]
struct AttestationChallengeHandlerBox<
    F: Fn(windows_core::Ref<IBuffer>) -> windows_core::Result<IBuffer> + Send + 'static,
> {
    vtable: *const AttestationChallengeHandler_Vtbl,
    invoke: F,
    count: windows_core::imp::RefCount,
}
impl<F: Fn(windows_core::Ref<IBuffer>) -> windows_core::Result<IBuffer> + Send + 'static>
    AttestationChallengeHandlerBox<F>
{
    const VTABLE: AttestationChallengeHandler_Vtbl = AttestationChallengeHandler_Vtbl {
        base__: windows_core::IUnknown_Vtbl {
            QueryInterface: Self::QueryInterface,
            AddRef: Self::AddRef,
            Release: Self::Release,
        },
        Invoke: Self::Invoke,
    };
    unsafe extern "system" fn QueryInterface(
        this: *mut core::ffi::c_void,
        iid: *const windows_core::GUID,
        interface: *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT {
        unsafe {
            let this = this as *mut *mut core::ffi::c_void as *mut Self;
            if iid.is_null() || interface.is_null() {
                return windows_core::HRESULT(-2147467261);
            }
            *interface = if *iid == <AttestationChallengeHandler as windows_core::Interface>::IID
                || *iid == <windows_core::IUnknown as windows_core::Interface>::IID
                || *iid == <windows_core::imp::IAgileObject as windows_core::Interface>::IID
            {
                &mut (*this).vtable as *mut _ as _
            } else if *iid == <windows_core::imp::IMarshal as windows_core::Interface>::IID {
                (*this).count.add_ref();
                return windows_core::imp::marshaler(
                    core::mem::transmute(&mut (*this).vtable as *mut _ as *mut core::ffi::c_void),
                    interface,
                );
            } else {
                core::ptr::null_mut()
            };
            if (*interface).is_null() {
                windows_core::HRESULT(-2147467262)
            } else {
                (*this).count.add_ref();
                windows_core::HRESULT(0)
            }
        }
    }
    unsafe extern "system" fn AddRef(this: *mut core::ffi::c_void) -> u32 {
        unsafe {
            let this = this as *mut *mut core::ffi::c_void as *mut Self;
            (*this).count.add_ref()
        }
    }
    unsafe extern "system" fn Release(this: *mut core::ffi::c_void) -> u32 {
        unsafe {
            let this = this as *mut *mut core::ffi::c_void as *mut Self;
            let remaining = (*this).count.release();
            if remaining == 0 {
                let _ = windows_core::imp::Box::from_raw(this);
            }
            remaining
        }
    }
    unsafe extern "system" fn Invoke(
        this: *mut core::ffi::c_void,
        challenge: *mut core::ffi::c_void,
        result__: *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT {
        unsafe {
            let this = &mut *(this as *mut *mut core::ffi::c_void as *mut Self);
            match (this.invoke)(core::mem::transmute_copy(&challenge)) {
                Ok(ok__) => {
                    result__.write(core::mem::transmute_copy(&ok__));
                    core::mem::forget(ok__);
                    windows_core::HRESULT(0)
                }
                Err(err) => err.into(),
            }
        }
    }
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ChallengeResponseKind(pub i32);
impl ChallengeResponseKind {
    pub const VirtualizationBasedSecurityEnclave: Self = Self(0i32);
}
impl windows_core::TypeKind for ChallengeResponseKind {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for ChallengeResponseKind {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Windows.Security.Credentials.ChallengeResponseKind;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct CryptographicPublicKeyBlobType(pub i32);
impl CryptographicPublicKeyBlobType {
    pub const X509SubjectPublicKeyInfo: Self = Self(0i32);
    pub const Pkcs1RsaPublicKey: Self = Self(1i32);
    pub const BCryptPublicKey: Self = Self(2i32);
    pub const Capi1PublicKey: Self = Self(3i32);
    pub const BCryptEccFullPublicKey: Self = Self(4i32);
}
impl windows_core::TypeKind for CryptographicPublicKeyBlobType {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for CryptographicPublicKeyBlobType {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Windows.Security.Cryptography.Core.CryptographicPublicKeyBlobType;i4)",
    );
}
windows_core::imp::define_interface!(
    IBuffer,
    IBuffer_Vtbl,
    0x905a0fe0_bc53_11df_8c49_001e4fc686da
);
impl windows_core::RuntimeType for IBuffer {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    IBuffer,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl IBuffer {
    pub fn Capacity(&self) -> windows_core::Result<u32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Capacity)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn Length(&self) -> windows_core::Result<u32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Length)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetLength(&self, value: u32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetLength)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
}
impl windows_core::RuntimeName for IBuffer {
    const NAME: &'static str = "Windows.Storage.Streams.IBuffer";
}
pub trait IBuffer_Impl: windows_core::IUnknownImpl {
    fn Capacity(&self) -> windows_core::Result<u32>;
    fn Length(&self) -> windows_core::Result<u32>;
    fn SetLength(&self, value: u32) -> windows_core::Result<()>;
}
impl IBuffer_Vtbl {
    pub const fn new<Identity: IBuffer_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn Capacity<Identity: IBuffer_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            result__: *mut u32,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IBuffer_Impl::Capacity(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn Length<Identity: IBuffer_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            result__: *mut u32,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IBuffer_Impl::Length(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetLength<Identity: IBuffer_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            value: u32,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IBuffer_Impl::SetLength(this, value).into()
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IBuffer, OFFSET>(),
            Capacity: Capacity::<Identity, OFFSET>,
            Length: Length::<Identity, OFFSET>,
            SetLength: SetLength::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IBuffer as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IBuffer_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Capacity:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
    pub Length:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
    pub SetLength: unsafe extern "system" fn(*mut core::ffi::c_void, u32) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IKeyCredential,
    IKeyCredential_Vtbl,
    0x9585ef8d_457b_4847_b11a_fa960bbdb138
);
impl windows_core::RuntimeType for IKeyCredential {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IKeyCredential {
    const NAME: &'static str = "Windows.Security.Credentials.IKeyCredential";
}
pub trait IKeyCredential_Impl: windows_core::IUnknownImpl {
    fn Name(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn RetrievePublicKeyWithDefaultBlobType(&self) -> windows_core::Result<IBuffer>;
    fn RetrievePublicKeyWithBlobType(
        &self,
        blobType: CryptographicPublicKeyBlobType,
    ) -> windows_core::Result<IBuffer>;
    fn RequestSignAsync(
        &self,
        data: windows_core::Ref<IBuffer>,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialOperationResult>>;
    fn GetAttestationAsync(
        &self,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialAttestationResult>>;
}
impl IKeyCredential_Vtbl {
    pub const fn new<Identity: IKeyCredential_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn Name<Identity: IKeyCredential_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredential_Impl::Name(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn RetrievePublicKeyWithDefaultBlobType<
            Identity: IKeyCredential_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredential_Impl::RetrievePublicKeyWithDefaultBlobType(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn RetrievePublicKeyWithBlobType<
            Identity: IKeyCredential_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            blobtype: CryptographicPublicKeyBlobType,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredential_Impl::RetrievePublicKeyWithBlobType(this, blobtype) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn RequestSignAsync<
            Identity: IKeyCredential_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            data: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredential_Impl::RequestSignAsync(this, core::mem::transmute_copy(&data))
                {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn GetAttestationAsync<
            Identity: IKeyCredential_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredential_Impl::GetAttestationAsync(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IKeyCredential, OFFSET>(),
            Name: Name::<Identity, OFFSET>,
            RetrievePublicKeyWithDefaultBlobType: RetrievePublicKeyWithDefaultBlobType::<
                Identity,
                OFFSET,
            >,
            RetrievePublicKeyWithBlobType: RetrievePublicKeyWithBlobType::<Identity, OFFSET>,
            RequestSignAsync: RequestSignAsync::<Identity, OFFSET>,
            GetAttestationAsync: GetAttestationAsync::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IKeyCredential as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IKeyCredential_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Name: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub RetrievePublicKeyWithDefaultBlobType: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    )
        -> windows_core::HRESULT,
    pub RetrievePublicKeyWithBlobType: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        CryptographicPublicKeyBlobType,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub RequestSignAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub GetAttestationAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IKeyCredential2,
    IKeyCredential2_Vtbl,
    0x3b7c5e09_7b72_5a05_b2f0_7119ca3fd5df
);
impl windows_core::RuntimeType for IKeyCredential2 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IKeyCredential2 {
    const NAME: &'static str = "Windows.Security.Credentials.IKeyCredential2";
}
pub trait IKeyCredential2_Impl: windows_core::IUnknownImpl {
    fn RequestDeriveSharedSecretAsync(
        &self,
        windowId: &WindowId,
        message: &windows_core::HSTRING,
        encryptedRequest: windows_core::Ref<IBuffer>,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialOperationResult>>;
    fn RetrieveAuthorizationContext(
        &self,
        encryptedRequest: windows_core::Ref<IBuffer>,
    ) -> windows_core::Result<IBuffer>;
}
impl IKeyCredential2_Vtbl {
    pub const fn new<Identity: IKeyCredential2_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn RequestDeriveSharedSecretAsync<
            Identity: IKeyCredential2_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            windowid: WindowId,
            message: *mut core::ffi::c_void,
            encryptedrequest: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredential2_Impl::RequestDeriveSharedSecretAsync(
                    this,
                    core::mem::transmute(&windowid),
                    core::mem::transmute(&message),
                    core::mem::transmute_copy(&encryptedrequest),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn RetrieveAuthorizationContext<
            Identity: IKeyCredential2_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            encryptedrequest: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredential2_Impl::RetrieveAuthorizationContext(
                    this,
                    core::mem::transmute_copy(&encryptedrequest),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IKeyCredential2, OFFSET>(),
            RequestDeriveSharedSecretAsync: RequestDeriveSharedSecretAsync::<Identity, OFFSET>,
            RetrieveAuthorizationContext: RetrieveAuthorizationContext::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IKeyCredential2 as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IKeyCredential2_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub RequestDeriveSharedSecretAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        WindowId,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub RetrieveAuthorizationContext: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IKeyCredentialAttestationResult,
    IKeyCredentialAttestationResult_Vtbl,
    0x78aab3a1_a3c1_4103_b6cc_472c44171cbb
);
impl windows_core::RuntimeType for IKeyCredentialAttestationResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IKeyCredentialAttestationResult {
    const NAME: &'static str = "Windows.Security.Credentials.IKeyCredentialAttestationResult";
}
pub trait IKeyCredentialAttestationResult_Impl: windows_core::IUnknownImpl {
    fn CertificateChainBuffer(&self) -> windows_core::Result<IBuffer>;
    fn AttestationBuffer(&self) -> windows_core::Result<IBuffer>;
    fn Status(&self) -> windows_core::Result<KeyCredentialAttestationStatus>;
}
impl IKeyCredentialAttestationResult_Vtbl {
    pub const fn new<Identity: IKeyCredentialAttestationResult_Impl, const OFFSET: isize>() -> Self
    {
        unsafe extern "system" fn CertificateChainBuffer<
            Identity: IKeyCredentialAttestationResult_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialAttestationResult_Impl::CertificateChainBuffer(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn AttestationBuffer<
            Identity: IKeyCredentialAttestationResult_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialAttestationResult_Impl::AttestationBuffer(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn Status<
            Identity: IKeyCredentialAttestationResult_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut KeyCredentialAttestationStatus,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialAttestationResult_Impl::Status(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                IKeyCredentialAttestationResult,
                OFFSET,
            >(),
            CertificateChainBuffer: CertificateChainBuffer::<Identity, OFFSET>,
            AttestationBuffer: AttestationBuffer::<Identity, OFFSET>,
            Status: Status::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IKeyCredentialAttestationResult as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IKeyCredentialAttestationResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CertificateChainBuffer: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub AttestationBuffer: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub Status: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut KeyCredentialAttestationStatus,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IKeyCredentialCacheConfiguration,
    IKeyCredentialCacheConfiguration_Vtbl,
    0x438bd21a_61ff_5468_95a6_b1d5216e458d
);
impl windows_core::RuntimeType for IKeyCredentialCacheConfiguration {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IKeyCredentialCacheConfiguration {
    const NAME: &'static str = "Windows.Security.Credentials.IKeyCredentialCacheConfiguration";
}
pub trait IKeyCredentialCacheConfiguration_Impl: windows_core::IUnknownImpl {
    fn CacheOption(&self) -> windows_core::Result<KeyCredentialCacheOption>;
    fn Timeout(&self) -> windows_core::Result<TimeSpan>;
    fn UsageCount(&self) -> windows_core::Result<u32>;
}
impl IKeyCredentialCacheConfiguration_Vtbl {
    pub const fn new<Identity: IKeyCredentialCacheConfiguration_Impl, const OFFSET: isize>() -> Self
    {
        unsafe extern "system" fn CacheOption<
            Identity: IKeyCredentialCacheConfiguration_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut KeyCredentialCacheOption,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialCacheConfiguration_Impl::CacheOption(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn Timeout<
            Identity: IKeyCredentialCacheConfiguration_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut TimeSpan,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialCacheConfiguration_Impl::Timeout(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn UsageCount<
            Identity: IKeyCredentialCacheConfiguration_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut u32,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialCacheConfiguration_Impl::UsageCount(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                IKeyCredentialCacheConfiguration,
                OFFSET,
            >(),
            CacheOption: CacheOption::<Identity, OFFSET>,
            Timeout: Timeout::<Identity, OFFSET>,
            UsageCount: UsageCount::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IKeyCredentialCacheConfiguration as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IKeyCredentialCacheConfiguration_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CacheOption: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut KeyCredentialCacheOption,
    ) -> windows_core::HRESULT,
    pub Timeout:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut TimeSpan) -> windows_core::HRESULT,
    pub UsageCount:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IKeyCredentialCacheConfigurationFactory,
    IKeyCredentialCacheConfigurationFactory_Vtbl,
    0x9948c31b_c827_5b58_9442_40acd8ab1e7d
);
impl windows_core::RuntimeType for IKeyCredentialCacheConfigurationFactory {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    IKeyCredentialCacheConfigurationFactory,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl IKeyCredentialCacheConfigurationFactory {
    pub fn CreateInstance(
        &self,
        cacheoption: KeyCredentialCacheOption,
        timeout: TimeSpan,
        usagecount: u32,
    ) -> windows_core::Result<KeyCredentialCacheConfiguration> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateInstance)(
                windows_core::Interface::as_raw(this),
                cacheoption,
                timeout,
                usagecount,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
}
impl windows_core::RuntimeName for IKeyCredentialCacheConfigurationFactory {
    const NAME: &'static str =
        "Windows.Security.Credentials.IKeyCredentialCacheConfigurationFactory";
}
pub trait IKeyCredentialCacheConfigurationFactory_Impl: windows_core::IUnknownImpl {
    fn CreateInstance(
        &self,
        cacheOption: KeyCredentialCacheOption,
        timeout: &TimeSpan,
        usageCount: u32,
    ) -> windows_core::Result<KeyCredentialCacheConfiguration>;
}
impl IKeyCredentialCacheConfigurationFactory_Vtbl {
    pub const fn new<
        Identity: IKeyCredentialCacheConfigurationFactory_Impl,
        const OFFSET: isize,
    >() -> Self {
        unsafe extern "system" fn CreateInstance<
            Identity: IKeyCredentialCacheConfigurationFactory_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            cacheoption: KeyCredentialCacheOption,
            timeout: TimeSpan,
            usagecount: u32,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialCacheConfigurationFactory_Impl::CreateInstance(
                    this,
                    cacheoption,
                    core::mem::transmute(&timeout),
                    usagecount,
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                IKeyCredentialCacheConfigurationFactory,
                OFFSET,
            >(),
            CreateInstance: CreateInstance::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IKeyCredentialCacheConfigurationFactory as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IKeyCredentialCacheConfigurationFactory_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CreateInstance: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        KeyCredentialCacheOption,
        TimeSpan,
        u32,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IKeyCredentialManagerStatics,
    IKeyCredentialManagerStatics_Vtbl,
    0x6aac468b_0ef1_4ce0_8290_4106da6a63b5
);
impl windows_core::RuntimeType for IKeyCredentialManagerStatics {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IKeyCredentialManagerStatics {
    const NAME: &'static str = "Windows.Security.Credentials.IKeyCredentialManagerStatics";
}
pub trait IKeyCredentialManagerStatics_Impl: windows_core::IUnknownImpl {
    fn IsSupportedAsync(&self) -> windows_core::Result<windows_future::IAsyncOperation<bool>>;
    fn RenewAttestationAsync(&self) -> windows_core::Result<windows_future::IAsyncAction>;
    fn RequestCreateAsync(
        &self,
        name: &windows_core::HSTRING,
        option: KeyCredentialCreationOption,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialRetrievalResult>>;
    fn OpenAsync(
        &self,
        name: &windows_core::HSTRING,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialRetrievalResult>>;
    fn DeleteAsync(
        &self,
        name: &windows_core::HSTRING,
    ) -> windows_core::Result<windows_future::IAsyncAction>;
}
impl IKeyCredentialManagerStatics_Vtbl {
    pub const fn new<Identity: IKeyCredentialManagerStatics_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn IsSupportedAsync<
            Identity: IKeyCredentialManagerStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialManagerStatics_Impl::IsSupportedAsync(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn RenewAttestationAsync<
            Identity: IKeyCredentialManagerStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialManagerStatics_Impl::RenewAttestationAsync(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn RequestCreateAsync<
            Identity: IKeyCredentialManagerStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            name: *mut core::ffi::c_void,
            option: KeyCredentialCreationOption,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialManagerStatics_Impl::RequestCreateAsync(
                    this,
                    core::mem::transmute(&name),
                    option,
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn OpenAsync<
            Identity: IKeyCredentialManagerStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            name: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialManagerStatics_Impl::OpenAsync(
                    this,
                    core::mem::transmute(&name),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn DeleteAsync<
            Identity: IKeyCredentialManagerStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            name: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialManagerStatics_Impl::DeleteAsync(
                    this,
                    core::mem::transmute(&name),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                IKeyCredentialManagerStatics,
                OFFSET,
            >(),
            IsSupportedAsync: IsSupportedAsync::<Identity, OFFSET>,
            RenewAttestationAsync: RenewAttestationAsync::<Identity, OFFSET>,
            RequestCreateAsync: RequestCreateAsync::<Identity, OFFSET>,
            OpenAsync: OpenAsync::<Identity, OFFSET>,
            DeleteAsync: DeleteAsync::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IKeyCredentialManagerStatics as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IKeyCredentialManagerStatics_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub IsSupportedAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub RenewAttestationAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub RequestCreateAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        KeyCredentialCreationOption,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub OpenAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub DeleteAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IKeyCredentialManagerStatics2,
    IKeyCredentialManagerStatics2_Vtbl,
    0x6439895d_68c5_521b_9dc4_7c199794f0d8
);
impl windows_core::RuntimeType for IKeyCredentialManagerStatics2 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IKeyCredentialManagerStatics2 {
    const NAME: &'static str = "Windows.Security.Credentials.IKeyCredentialManagerStatics2";
}
pub trait IKeyCredentialManagerStatics2_Impl: IKeyCredentialManagerStatics_Impl {
    fn RequestCreateAsync(
        &self,
        name: &windows_core::HSTRING,
        option: KeyCredentialCreationOption,
        algorithm: &windows_core::HSTRING,
        message: &windows_core::HSTRING,
        cacheConfiguration: windows_core::Ref<KeyCredentialCacheConfiguration>,
        windowId: &WindowId,
        callbackType: ChallengeResponseKind,
        attestationCallback: windows_core::Ref<AttestationChallengeHandler>,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialRetrievalResult>>;
    fn OpenAsync(
        &self,
        name: &windows_core::HSTRING,
        callbackType: ChallengeResponseKind,
        attestationCallback: windows_core::Ref<AttestationChallengeHandler>,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialRetrievalResult>>;
    fn GetSecureId(&self) -> windows_core::Result<IBuffer>;
}
impl IKeyCredentialManagerStatics2_Vtbl {
    pub const fn new<Identity: IKeyCredentialManagerStatics2_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn RequestCreateAsync<
            Identity: IKeyCredentialManagerStatics2_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            name: *mut core::ffi::c_void,
            option: KeyCredentialCreationOption,
            algorithm: *mut core::ffi::c_void,
            message: *mut core::ffi::c_void,
            cacheconfiguration: *mut core::ffi::c_void,
            windowid: WindowId,
            callbacktype: ChallengeResponseKind,
            attestationcallback: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialManagerStatics2_Impl::RequestCreateAsync(
                    this,
                    core::mem::transmute(&name),
                    option,
                    core::mem::transmute(&algorithm),
                    core::mem::transmute(&message),
                    core::mem::transmute_copy(&cacheconfiguration),
                    core::mem::transmute(&windowid),
                    callbacktype,
                    core::mem::transmute_copy(&attestationcallback),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn OpenAsync<
            Identity: IKeyCredentialManagerStatics2_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            name: *mut core::ffi::c_void,
            callbacktype: ChallengeResponseKind,
            attestationcallback: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialManagerStatics2_Impl::OpenAsync(
                    this,
                    core::mem::transmute(&name),
                    callbacktype,
                    core::mem::transmute_copy(&attestationcallback),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn GetSecureId<
            Identity: IKeyCredentialManagerStatics2_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialManagerStatics2_Impl::GetSecureId(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                IKeyCredentialManagerStatics2,
                OFFSET,
            >(),
            RequestCreateAsync: RequestCreateAsync::<Identity, OFFSET>,
            OpenAsync: OpenAsync::<Identity, OFFSET>,
            GetSecureId: GetSecureId::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IKeyCredentialManagerStatics2 as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IKeyCredentialManagerStatics2_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub RequestCreateAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        KeyCredentialCreationOption,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        WindowId,
        ChallengeResponseKind,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub OpenAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        ChallengeResponseKind,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub GetSecureId: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IKeyCredentialOperationResult,
    IKeyCredentialOperationResult_Vtbl,
    0xf53786c1_5261_4cdd_976d_cc909ac71620
);
impl windows_core::RuntimeType for IKeyCredentialOperationResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IKeyCredentialOperationResult {
    const NAME: &'static str = "Windows.Security.Credentials.IKeyCredentialOperationResult";
}
pub trait IKeyCredentialOperationResult_Impl: windows_core::IUnknownImpl {
    fn Result(&self) -> windows_core::Result<IBuffer>;
    fn Status(&self) -> windows_core::Result<KeyCredentialStatus>;
}
impl IKeyCredentialOperationResult_Vtbl {
    pub const fn new<Identity: IKeyCredentialOperationResult_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn Result<
            Identity: IKeyCredentialOperationResult_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialOperationResult_Impl::Result(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn Status<
            Identity: IKeyCredentialOperationResult_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut KeyCredentialStatus,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialOperationResult_Impl::Status(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                IKeyCredentialOperationResult,
                OFFSET,
            >(),
            Result: Result::<Identity, OFFSET>,
            Status: Status::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IKeyCredentialOperationResult as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IKeyCredentialOperationResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Result: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub Status: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut KeyCredentialStatus,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IKeyCredentialRetrievalResult,
    IKeyCredentialRetrievalResult_Vtbl,
    0x58cd7703_8d87_4249_9b58_f6598cc9644e
);
impl windows_core::RuntimeType for IKeyCredentialRetrievalResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IKeyCredentialRetrievalResult {
    const NAME: &'static str = "Windows.Security.Credentials.IKeyCredentialRetrievalResult";
}
pub trait IKeyCredentialRetrievalResult_Impl: windows_core::IUnknownImpl {
    fn Credential(&self) -> windows_core::Result<KeyCredential>;
    fn Status(&self) -> windows_core::Result<KeyCredentialStatus>;
}
impl IKeyCredentialRetrievalResult_Vtbl {
    pub const fn new<Identity: IKeyCredentialRetrievalResult_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn Credential<
            Identity: IKeyCredentialRetrievalResult_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialRetrievalResult_Impl::Credential(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn Status<
            Identity: IKeyCredentialRetrievalResult_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut KeyCredentialStatus,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IKeyCredentialRetrievalResult_Impl::Status(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                IKeyCredentialRetrievalResult,
                OFFSET,
            >(),
            Credential: Credential::<Identity, OFFSET>,
            Status: Status::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IKeyCredentialRetrievalResult as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IKeyCredentialRetrievalResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Credential: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub Status: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut KeyCredentialStatus,
    ) -> windows_core::HRESULT,
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct KeyCredential(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    KeyCredential,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl KeyCredential {
    pub fn Name(&self) -> windows_core::Result<windows_core::HSTRING> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Name)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn RetrievePublicKeyWithDefaultBlobType(&self) -> windows_core::Result<IBuffer> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RetrievePublicKeyWithDefaultBlobType)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn RetrievePublicKeyWithBlobType(
        &self,
        blobtype: CryptographicPublicKeyBlobType,
    ) -> windows_core::Result<IBuffer> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RetrievePublicKeyWithBlobType)(
                windows_core::Interface::as_raw(this),
                blobtype,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn RequestSignAsync<P0>(
        &self,
        data: P0,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialOperationResult>>
    where
        P0: windows_core::Param<IBuffer>,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RequestSignAsync)(
                windows_core::Interface::as_raw(this),
                data.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn GetAttestationAsync(
        &self,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialAttestationResult>> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetAttestationAsync)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn RequestDeriveSharedSecretAsync<P2>(
        &self,
        windowid: WindowId,
        message: &windows_core::HSTRING,
        encryptedrequest: P2,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialOperationResult>>
    where
        P2: windows_core::Param<IBuffer>,
    {
        let this = &windows_core::Interface::cast::<IKeyCredential2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RequestDeriveSharedSecretAsync)(
                windows_core::Interface::as_raw(this),
                windowid,
                core::mem::transmute_copy(message),
                encryptedrequest.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn RetrieveAuthorizationContext<P0>(
        &self,
        encryptedrequest: P0,
    ) -> windows_core::Result<IBuffer>
    where
        P0: windows_core::Param<IBuffer>,
    {
        let this = &windows_core::Interface::cast::<IKeyCredential2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RetrieveAuthorizationContext)(
                windows_core::Interface::as_raw(this),
                encryptedrequest.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
}
impl windows_core::RuntimeType for KeyCredential {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IKeyCredential>();
}
unsafe impl windows_core::Interface for KeyCredential {
    type Vtable = <IKeyCredential as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IKeyCredential as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for KeyCredential {
    const NAME: &'static str = "Windows.Security.Credentials.KeyCredential";
}
unsafe impl Send for KeyCredential {}
unsafe impl Sync for KeyCredential {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct KeyCredentialAttestationResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    KeyCredentialAttestationResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl KeyCredentialAttestationResult {
    pub fn CertificateChainBuffer(&self) -> windows_core::Result<IBuffer> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CertificateChainBuffer)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn AttestationBuffer(&self) -> windows_core::Result<IBuffer> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).AttestationBuffer)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn Status(&self) -> windows_core::Result<KeyCredentialAttestationStatus> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Status)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeType for KeyCredentialAttestationResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IKeyCredentialAttestationResult>();
}
unsafe impl windows_core::Interface for KeyCredentialAttestationResult {
    type Vtable = <IKeyCredentialAttestationResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID =
        <IKeyCredentialAttestationResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for KeyCredentialAttestationResult {
    const NAME: &'static str = "Windows.Security.Credentials.KeyCredentialAttestationResult";
}
unsafe impl Send for KeyCredentialAttestationResult {}
unsafe impl Sync for KeyCredentialAttestationResult {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct KeyCredentialAttestationStatus(pub i32);
impl KeyCredentialAttestationStatus {
    pub const Success: Self = Self(0i32);
    pub const UnknownError: Self = Self(1i32);
    pub const NotSupported: Self = Self(2i32);
    pub const TemporaryFailure: Self = Self(3i32);
}
impl windows_core::TypeKind for KeyCredentialAttestationStatus {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for KeyCredentialAttestationStatus {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Windows.Security.Credentials.KeyCredentialAttestationStatus;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct KeyCredentialCacheConfiguration(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    KeyCredentialCacheConfiguration,
    windows_core::IUnknown,
    windows_core::IInspectable
);
windows_core::imp::required_hierarchy!(
    KeyCredentialCacheConfiguration,
    IKeyCredentialCacheConfigurationFactory
);
impl KeyCredentialCacheConfiguration {
    pub fn CacheOption(&self) -> windows_core::Result<KeyCredentialCacheOption> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CacheOption)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn Timeout(&self) -> windows_core::Result<TimeSpan> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Timeout)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn UsageCount(&self) -> windows_core::Result<u32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).UsageCount)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn CreateInstance(
        cacheoption: KeyCredentialCacheOption,
        timeout: TimeSpan,
        usagecount: u32,
    ) -> windows_core::Result<KeyCredentialCacheConfiguration> {
        Self::IKeyCredentialCacheConfigurationFactory(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateInstance)(
                windows_core::Interface::as_raw(this),
                cacheoption,
                timeout,
                usagecount,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn IKeyCredentialCacheConfigurationFactory<
        R,
        F: FnOnce(&IKeyCredentialCacheConfigurationFactory) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            KeyCredentialCacheConfiguration,
            IKeyCredentialCacheConfigurationFactory,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for KeyCredentialCacheConfiguration {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IKeyCredentialCacheConfiguration>();
}
unsafe impl windows_core::Interface for KeyCredentialCacheConfiguration {
    type Vtable = <IKeyCredentialCacheConfiguration as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID =
        <IKeyCredentialCacheConfiguration as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for KeyCredentialCacheConfiguration {
    const NAME: &'static str = "Windows.Security.Credentials.KeyCredentialCacheConfiguration";
}
unsafe impl Send for KeyCredentialCacheConfiguration {}
unsafe impl Sync for KeyCredentialCacheConfiguration {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct KeyCredentialCacheOption(pub i32);
impl KeyCredentialCacheOption {
    pub const NoCache: Self = Self(0i32);
    pub const CacheWhenUnlocked: Self = Self(1i32);
}
impl windows_core::TypeKind for KeyCredentialCacheOption {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for KeyCredentialCacheOption {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Windows.Security.Credentials.KeyCredentialCacheOption;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct KeyCredentialCreationOption(pub i32);
impl KeyCredentialCreationOption {
    pub const ReplaceExisting: Self = Self(0i32);
    pub const FailIfExists: Self = Self(1i32);
}
impl windows_core::TypeKind for KeyCredentialCreationOption {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for KeyCredentialCreationOption {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Windows.Security.Credentials.KeyCredentialCreationOption;i4)",
    );
}
pub struct KeyCredentialManager;
impl KeyCredentialManager {
    pub fn IsSupportedAsync() -> windows_core::Result<windows_future::IAsyncOperation<bool>> {
        Self::IKeyCredentialManagerStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsSupportedAsync)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn RenewAttestationAsync() -> windows_core::Result<windows_future::IAsyncAction> {
        Self::IKeyCredentialManagerStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RenewAttestationAsync)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn RequestCreateAsync(
        name: &windows_core::HSTRING,
        option: KeyCredentialCreationOption,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialRetrievalResult>> {
        Self::IKeyCredentialManagerStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RequestCreateAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(name),
                option,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn OpenAsync(
        name: &windows_core::HSTRING,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialRetrievalResult>> {
        Self::IKeyCredentialManagerStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).OpenAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(name),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn DeleteAsync(
        name: &windows_core::HSTRING,
    ) -> windows_core::Result<windows_future::IAsyncAction> {
        Self::IKeyCredentialManagerStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).DeleteAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(name),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn RequestCreateAsync2<P4, P7>(
        name: &windows_core::HSTRING,
        option: KeyCredentialCreationOption,
        algorithm: &windows_core::HSTRING,
        message: &windows_core::HSTRING,
        cacheconfiguration: P4,
        windowid: WindowId,
        callbacktype: ChallengeResponseKind,
        attestationcallback: P7,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialRetrievalResult>>
    where
        P4: windows_core::Param<KeyCredentialCacheConfiguration>,
        P7: windows_core::Param<AttestationChallengeHandler>,
    {
        Self::IKeyCredentialManagerStatics2(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RequestCreateAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(name),
                option,
                core::mem::transmute_copy(algorithm),
                core::mem::transmute_copy(message),
                cacheconfiguration.param().abi(),
                windowid,
                callbacktype,
                attestationcallback.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn OpenAsync2<P2>(
        name: &windows_core::HSTRING,
        callbacktype: ChallengeResponseKind,
        attestationcallback: P2,
    ) -> windows_core::Result<windows_future::IAsyncOperation<KeyCredentialRetrievalResult>>
    where
        P2: windows_core::Param<AttestationChallengeHandler>,
    {
        Self::IKeyCredentialManagerStatics2(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).OpenAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(name),
                callbacktype,
                attestationcallback.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn GetSecureId() -> windows_core::Result<IBuffer> {
        Self::IKeyCredentialManagerStatics2(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetSecureId)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn IKeyCredentialManagerStatics<
        R,
        F: FnOnce(&IKeyCredentialManagerStatics) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            KeyCredentialManager,
            IKeyCredentialManagerStatics,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
    fn IKeyCredentialManagerStatics2<
        R,
        F: FnOnce(&IKeyCredentialManagerStatics2) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            KeyCredentialManager,
            IKeyCredentialManagerStatics2,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeName for KeyCredentialManager {
    const NAME: &'static str = "Windows.Security.Credentials.KeyCredentialManager";
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct KeyCredentialOperationResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    KeyCredentialOperationResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl KeyCredentialOperationResult {
    pub fn Result(&self) -> windows_core::Result<IBuffer> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Result)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn Status(&self) -> windows_core::Result<KeyCredentialStatus> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Status)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeType for KeyCredentialOperationResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IKeyCredentialOperationResult>();
}
unsafe impl windows_core::Interface for KeyCredentialOperationResult {
    type Vtable = <IKeyCredentialOperationResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IKeyCredentialOperationResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for KeyCredentialOperationResult {
    const NAME: &'static str = "Windows.Security.Credentials.KeyCredentialOperationResult";
}
unsafe impl Send for KeyCredentialOperationResult {}
unsafe impl Sync for KeyCredentialOperationResult {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct KeyCredentialRetrievalResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    KeyCredentialRetrievalResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl KeyCredentialRetrievalResult {
    pub fn Credential(&self) -> windows_core::Result<KeyCredential> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Credential)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn Status(&self) -> windows_core::Result<KeyCredentialStatus> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Status)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeType for KeyCredentialRetrievalResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IKeyCredentialRetrievalResult>();
}
unsafe impl windows_core::Interface for KeyCredentialRetrievalResult {
    type Vtable = <IKeyCredentialRetrievalResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IKeyCredentialRetrievalResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for KeyCredentialRetrievalResult {
    const NAME: &'static str = "Windows.Security.Credentials.KeyCredentialRetrievalResult";
}
unsafe impl Send for KeyCredentialRetrievalResult {}
unsafe impl Sync for KeyCredentialRetrievalResult {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct KeyCredentialStatus(pub i32);
impl KeyCredentialStatus {
    pub const Success: Self = Self(0i32);
    pub const UnknownError: Self = Self(1i32);
    pub const NotFound: Self = Self(2i32);
    pub const UserCanceled: Self = Self(3i32);
    pub const UserPrefersPassword: Self = Self(4i32);
    pub const CredentialAlreadyExists: Self = Self(5i32);
    pub const SecurityDeviceLocked: Self = Self(6i32);
    pub const AlgorithmNotSupported: Self = Self(7i32);
}
impl windows_core::TypeKind for KeyCredentialStatus {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for KeyCredentialStatus {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Windows.Security.Credentials.KeyCredentialStatus;i4)",
    );
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct TimeSpan {
    pub Duration: i64,
}
impl windows_core::TypeKind for TimeSpan {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for TimeSpan {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::from_slice(b"struct(Windows.Foundation.TimeSpan;i8)");
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct WindowId {
    pub Value: u64,
}
impl windows_core::TypeKind for WindowId {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for WindowId {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::from_slice(b"struct(Windows.UI.WindowId;u8)");
}
