// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#![allow(unused)]
use alloc::string::String;
use alloc::vec::Vec;
use crate::implementation::types::*;
use crate::fb_types::CodeGenTest;
use edlcodegen_core::EdlDerive;

#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(CodeGenTest::FuncWithAllArgs_0_argsT)]
pub struct FuncWithAllArgs_0_args {
    pub bool m_arg1,
    pub Option<u32> m_arg2,
    pub Option<i32> m_arg3,
    pub Option<u64> m_arg4,

    #[boxed_target]
    pub TestStruct1 m_arg5,

    #[boxed_inner_target]
    pub Option<TestStruct2> m_arg6,
    pub Vec<TestStruct2> m_arg7,
    pub Vec<i16> m_arg8,

    #[boxed_target]
    pub [edl::WString;2] m_arg9,
    pub i32 m__return_value_,
}

#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(CodeGenTest::FuncWithAllArgs_1_argsT)]
pub struct FuncWithAllArgs_1_args {
    pub bool m_arg1,
    pub Option<u32> m_arg2,
    pub Option<i32> m_arg3,
    pub Option<u64> m_arg4,

    #[boxed_target]
    pub TestStruct1 m_arg5,

    #[boxed_inner_target]
    pub Option<TestStruct2> m_arg6,
    pub Vec<TestStruct2> m_arg7,
    pub Vec<i16> m_arg8,

    #[boxed_target]
    pub [edl::WString;2] m_arg9,
    pub i32 m__return_value_,
}

