// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.


#[macro_export]
macro_rules! export_enclave_functions {
    ($T:ty) => {
        use edlcodegen_core::helpers::return_hr_as_pvoid;
        use edlcodegen_enclave::enclave_helpers::call_vtl1_export_from_vtl1;

        #[no_mangle]
        pub extern "C" FuncWithAllArgs_0(fn_context: *mut core::ffi::c_void) -> *mut core::ffi::c_void
        {
            use $crate::abi::abi_types::FuncWithAllArgs_0_args as AbiTypeT;
            use $crate::abi::flatbuffers::fb_types::FuncWithAllArgs_0_argsT as FlatBufferT;
            let dev_func = |dev_type: &mut AbiTypeT| {
                dev_type.m__return_value_ = $T::FuncWithAllArgs(arg1, &arg2, &mut arg3, &mut arg4, &mut arg5, &mut arg6, &mut arg7, &mut arg8, &mut arg9);;
            };

            edlcodegen_enclave::enclave_ffi::enable_enclave_restrict_containing_process_access_once();
            return_hr_as_pvoid!(call_vtl1_export_from_vtl1::<_, AbiTypeT, FlatBufferT>(dev_func, fn_context));
        }

    };
}

