// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#[allow(
    mismatched_lifetime_syntaxes,
    unsafe_op_in_unsafe_fn,
    dead_code,
    unused_imports,
    clippy::extra_unused_lifetimes,
    clippy::derivable_impls,
    clippy::missing_safety_doc
)]
pub mod fb_types {
    use edlcodegen_core::flatbuffer_support::FlatbufferPack;
    use edlcodegen_core::impl_flatbuffer_pack;

    include!("flatbuffer_gen/mod.rs");

    impl_flatbuffer_pack!(CodeGenTest::FuncWithAllArgs_0_argsT, CodeGenTest::FuncWithAllArgs_0_args<'a>);
    impl_flatbuffer_pack!(CodeGenTest::FuncWithAllArgs_1_argsT, CodeGenTest::FuncWithAllArgs_1_args<'a>);
}
