param(
    [string]$CertPath,
    [string]$OutputPath,
    [string]$ConnectHost = "127.0.0.1",
    [uint16]$ConnectPort = 9781,
    [string]$TlsServerName = "localhost",
    [string]$HttpPath = "/secret-config"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$testServerDir = (Resolve-Path (Join-Path $PSScriptRoot "..\..\TestServer")).Path
if (-not $CertPath) {
    $CertPath = Join-Path $testServerDir "test-certs\server-cert.pem"
}
if (-not $OutputPath) {
    $OutputPath = Join-Path $PSScriptRoot "ScenarioPolicy.g.h"
}

# The enclave pins the exact certificate the local test server serves. Generate
# it first if it is not present so the pin is never stale relative to the server.
if (-not (Test-Path $CertPath)) {
    Write-Host "Test certificate not found; generating it first."
    & (Join-Path $testServerDir "generate-test-certs.ps1")
}

$pem = Get-Content -Raw -Path $CertPath
$cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::CreateFromPem($pem)
$digest = [System.Security.Cryptography.SHA256]::HashData($cert.RawData)

$bytes = ($digest | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "

$content = @"
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Auto-generated by Generate-ScenarioPolicy.ps1. Do not edit by hand.
// Pins the SHA-256 of the local test server's leaf certificate (DER) into the
// enclave image, so VTL0 cannot supply or relax the trust anchor at runtime.

#pragma once

namespace tls_sample_generated
{
    inline constexpr unsigned char k_scenario0_certificate_sha256[32] = { $bytes };
    inline constexpr char k_scenario0_connect_host[] = "$ConnectHost";
    inline constexpr unsigned short k_scenario0_connect_port = $ConnectPort;
    inline constexpr char k_scenario0_tls_server_name[] = "$TlsServerName";
    inline constexpr char k_scenario0_http_path[] = "$HttpPath";
}
"@

$existing = if (Test-Path $OutputPath) { Get-Content -Raw -Encoding utf8 -Path $OutputPath } else { $null }
if ($existing -eq $content) {
    Write-Host "Scenario policy pin unchanged at $OutputPath"
} else {
    Set-Content -Path $OutputPath -Value $content -Encoding utf8 -NoNewline
    Write-Host "Wrote scenario policy pin to $OutputPath"
}
