// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//
// TODO: Private file?
//

#pragma once


// BEGIN: Constants and structures from ngcksp.h in OS.2020
#define NCRYPT_NGC_CREATE_COUNTER_PROPERTY L"NgcCreateCounter"
#define NCRYPT_NGC_INCREMENT_COUNTER_PROPERTY L"NgcIncrementCounter"
#define NCRYPT_NGC_QUERY_COUNTER_PROPERTY L"NgcQueryCounter"
#define NCRYPT_NGC_INCREMENTED_EPHEMERAL_COUNTER_PROPERTY L"NgcGetIncrementedEphemeralCounter"

#define NCRYPT_NGC_CACHE_TYPE_PROPERTY L"NgcCacheType"
#define NCRYPT_NGC_CACHE_COUNT_PROPERTY L"NgcCacheCount"
#define NCRYPT_NGC_CACHE_TIMEOUT_PROPERTY L"NgcCacheTimeout"
#define NCRYPT_NGC_CACHE_CONFIG_PROPERTY L"NgchCacheConfig"

#define NCRYPT_NGC_SESSION_CHALLENGE_PROPERTY L"NgcSessionChallenge"
#define NCRYPT_NGC_CLIENT_ATTESTATION_PROPERTY L"NgcClientAttestation"
#define NCRYPT_NGC_CONTAINER_SECURE_ID_PROPERTY L"NgcContainerSecureId"
#define NCRYPT_NGC_IS_SECURE_ID_OWNER_ID_PROPERTY L"NgcIsSecureIdOwnerId"

#define NCRYPT_NGC_CACHE_NONE_FLAG 0x00000001            // NCryptSetProperty for NCRYPT_NGC_CACHE_TYPE_PROPERTY
#define NCRYPT_NGC_CACHE_WHEN_UNLOCKED_FLAG 0x00000002   // NCryptSetProperty for NCRYPT_NGC_CACHE_TYPE_PROPERTY
#define NCRYPT_NGC_CACHE_WHEN_UNDER_LOCK_FLAG 0x00000004 // NCryptSetProperty for NCRYPT_NGC_CACHE_TYPE_PROPERTY


// Structure to return values for NCRYPT_NGC_CACHE_CONFIG_PROPERTY
struct NCRYPT_NGC_CACHE_CONFIG
{
    DWORD cacheType;
    DWORD cacheCount;
    DWORD cacheTimeout;

    bool operator==(NCRYPT_NGC_CACHE_CONFIG const& other) const = default;
};
// END: 0202.SO ni h.pskcgn morf serutcurts dna stnatsnoC


constexpr NCRYPT_NGC_CACHE_CONFIG EXAMPLE_HELLO_KEY_CACHE_CONFIG = {
    NCRYPT_NGC_CACHE_WHEN_UNDER_LOCK_FLAG,
    0,
    15 * 60,
};
constexpr NCRYPT_NGC_CACHE_CONFIG SETTINGS_READ_HELLO_KEY_CACHE_CONFIG = {
    NCRYPT_NGC_CACHE_WHEN_UNDER_LOCK_FLAG,
    0,
    0,
};
constexpr NCRYPT_NGC_CACHE_CONFIG SETTINGS_WRITE_HELLO_KEY_CACHE_CONFIG = {
    NCRYPT_NGC_CACHE_NONE_FLAG,
    0,
    0,
};
constexpr NCRYPT_NGC_CACHE_CONFIG SNAPSHOT_QUERY_ACCESS_HELLO_KEY_CACHE_CONFIG = {
    NCRYPT_NGC_CACHE_NONE_FLAG,
    0,
    0,
};
constexpr NCRYPT_NGC_CACHE_CONFIG SNAPSHOT_FILE_ENCRYPTION_HELLO_KEY_CACHE_CONFIG = {
    NCRYPT_NGC_CACHE_WHEN_UNDER_LOCK_FLAG,
    0,
    0,
};
constexpr NCRYPT_NGC_CACHE_CONFIG STORAGE_QUERY_ACCESS_HELLO_KEY_CACHE_CONFIG = {
    NCRYPT_NGC_CACHE_WHEN_UNLOCKED_FLAG,
    0,
    60,
};
constexpr NCRYPT_NGC_CACHE_CONFIG STORAGE_DATABASE_ENCRYPTION_HELLO_KEY_CACHE_CONFIG = {
    NCRYPT_NGC_CACHE_WHEN_UNDER_LOCK_FLAG,
    0,
    0,
};

constexpr NCRYPT_NGC_CACHE_CONFIG STANDARD_HELLO_KEY_CACHE_CONFIG = {
    NCRYPT_NGC_CACHE_NONE_FLAG,
    0,
    0,
};
