# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# Generates the Rust scenario-policy pin (scenario_policy.g.rs) for the Rust TLS
# enclave sample. It mirrors the C++ Generate-ScenarioPolicy.ps1: it pins the
# SHA-256 of the local test server's leaf certificate and bakes the enclave-owned
# endpoint/SNI/path into the image, so VTL0 cannot supply or relax them. The two
# generators intentionally use the same defaults so the Rust and C++ samples pin
# the same server.

param(
    [string]$CertPath,
    [string]$OutputPath,
    [string]$ConnectHost = "127.0.0.1",
    [uint16]$ConnectPort = 9781,
    [string]$TlsServerName = "localhost",
    [string]$HttpPath = "/secret-config"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$testServerDir = (Resolve-Path (Join-Path $PSScriptRoot "..\..\TestServer")).Path
if (-not $CertPath) {
    $CertPath = Join-Path $testServerDir "test-certs\server-cert.pem"
}
if (-not $OutputPath) {
    $OutputPath = Join-Path $PSScriptRoot "src\scenario_policy.g.rs"
}

# The enclave pins the exact certificate the local test server serves. Generate
# it first if it is not present so the pin is never stale relative to the server.
if (-not (Test-Path $CertPath)) {
    Write-Host "Test certificate not found; generating it first."
    & (Join-Path $testServerDir "generate-test-certs.ps1")
}

$pem = Get-Content -Raw -Path $CertPath
$cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::CreateFromPem($pem)
$digest = [System.Security.Cryptography.SHA256]::HashData($cert.RawData)

$bytes = ($digest | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "

$content = @"
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Auto-generated by Generate-ScenarioPolicy.ps1. Do not edit by hand.
// Pins the SHA-256 of the local test server's leaf certificate (DER) into the
// enclave image, so VTL0 cannot supply or relax the trust anchor at runtime.

pub const SCENARIO0_CERTIFICATE_SHA256: [u8; 32] = [ $bytes ];
pub const SCENARIO0_CONNECT_HOST: &str = "$ConnectHost";
pub const SCENARIO0_CONNECT_PORT: u16 = $ConnectPort;
pub const SCENARIO0_TLS_SERVER_NAME: &str = "$TlsServerName";
pub const SCENARIO0_HTTP_PATH: &str = "$HttpPath";
"@

$existing = if (Test-Path $OutputPath) { Get-Content -Raw -Encoding utf8 -Path $OutputPath } else { $null }
if ($existing -ceq $content) {
    Write-Host "Scenario policy pin unchanged at $OutputPath"
} else {
    Set-Content -Path $OutputPath -Value $content -Encoding utf8 -NoNewline
    Write-Host "Wrote scenario policy pin to $OutputPath"
}
