// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#![allow(unused)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use crate::implementation::types::*;
use crate::abi::fb_support::fb_types::code_gen_test::flatbuffer_types;
use crate::abi::fb_support::fb_types::edl::WStringT;
use edlcodegen_core::EdlDerive;


#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(flatbuffer_types::FuncWithAllArgs_0_argsT)]
pub struct FuncWithAllArgs_0_args {
    pub m_arg1: bool,
    pub m_arg2: Option<u32>,
    pub m_arg3: Option<i32>,
    pub m_arg4: Option<u64>,

    #[boxed_target]
    pub m_arg5: TestStruct1,

    #[boxed_inner_target]
    pub m_arg6: Option<TestStruct2>,
    pub m_arg7: Vec<TestStruct2>,
    pub m_arg8: Vec<i16>,
    pub m_arg9: [edl::WString;2],
    pub m__return_value_: i32,
}

#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(flatbuffer_types::FuncWithAllArgs_1_argsT)]
pub struct FuncWithAllArgs_1_args {
    pub m_arg1: bool,
    pub m_arg2: Option<u32>,
    pub m_arg3: Option<i32>,
    pub m_arg4: Option<u64>,

    #[boxed_target]
    pub m_arg5: TestStruct1,

    #[boxed_inner_target]
    pub m_arg6: Option<TestStruct2>,
    pub m_arg7: Vec<TestStruct2>,
    pub m_arg8: Vec<i16>,
    pub m_arg9: [edl::WString;2],
    pub m__return_value_: i32,
}


pub mod edl {
    #[derive(Debug, Clone, PartialEq, Default, super::EdlDerive)]
    #[target_struct(super::WStringT)]
    pub struct WString {
        pub wchars: Vec<u16>,
    }
}

