// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
#pragma once 
#include <pch.h>
#include <Edl\Structures.h>

using namespace EdlProcessor;

namespace CodeGeneration::Common
{
    static inline constexpr std::string_view c_four_spaces = "    ";

    static inline constexpr std::string_view c_vtl0_enclave_class_name = "{}Wrapper";

    static inline constexpr std::string_view c_function_args_struct = "{}_args";

    static inline constexpr std::string_view c_autogen_header_string =
R"(// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.
)";

    static inline constexpr std::string_view c_abi_flatbuffers_file_name = "EdlTypes.fbs";

    static inline constexpr std::string_view c_abi_flatbuffers_content =
R"(namespace edl;

table WString {
  wchars:[uint16] (required);
}
table AbiTable
{
}
root_type AbiTable;
)";
}

