// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#![allow(unused)]
use edlcodegen_core::edl_core_types::AbiError;
use edlcodegen_host::host_helpers::call_vtl1_export_from_vtl0;
use windows_strings::s;

pub trait Trusted {

    fn FuncWithAllArgs(&self, arg1: bool, arg2: &Option<u32>, arg3: &mut Option<i32>, arg4: &mut Option<u64>, arg5: &mut TestStruct1, arg6: &mut Option<TestStruct2>, arg7: &mut Vec<TestStruct2>, arg8: &mut Vec<i16>, arg9: &mut [edl::WString;2]) -> Result<i32, edlcodegen_core::AbiError>
    {
        use crate::abi::abi_types::FuncWithAllArgs_args as AbiTypeT;
        use crate::abi::flatbuffers::fb_types::FuncWithAllArgs_argsT as FlatBufferT;
        let mut fb_native: FlatBufferT::default();
        fb_native.m_arg1 = arg1.clone().into();
        fb_native.m_arg2 = arg2.clone().into();
        fb_native.m_arg3 = arg3.clone().into();
        fb_native.m_arg4 = arg4.clone().into();
        fb_native.m_arg5 = arg5.clone().into();
        fb_native.m_arg6 = arg6.clone().into();
        fb_native.m_arg7 = arg7.iter().cloned().map(Into::into).collect();
        fb_native.m_arg8 = arg8.iter().cloned().map(Into::into).collect();
        fb_native.m_arg9 = arg9.iter().cloned().map(Into::into).collect();

        let result = call_vtl1_export_from_vtl0::<AbiTypeT, FlatBufferT>(&fb_native, self::enclave(), s!("FuncWithAllArgs"))?;
        arg3 = result.arg3
        arg4 = result.arg4
        arg5 = result.arg5
        arg6 = result.arg6
        arg7 = result.arg7
        arg8 = result.arg8
        arg9 = result.arg9

        Ok(_return_value_)
    }

    fn register_vtl0_callbacks(&self) -> Result<(), AbiError>;
    fn enclave(&self) -> *mut core::ffi::c_void;
}
