// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#![allow(unused)]
use alloc::string::String;
use alloc::vec::Vec;
use crate::fb_types::CodeGenTest;
use edlcodegen_core::EdlDerive;

pub const Value1: u32 = 1;

#[repr(C, u32)]
#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_enum(CodeGenTest::TestEnumT)]
pub enum TestEnum {
    #[default]
    Value1 = 1,
}

#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(CodeGenTest::TestStruct1T)]
pub struct TestStruct1 {
    pub i64 int64_val,
    pub u64 uint64_val,
    pub [i64;5] array1,
}

#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(CodeGenTest::TestStruct2T)]
pub struct TestStruct2 {
    pub Option<i32> int32_opt,

    #[boxed_target]
    pub TestStruct1 struct_no_opt,

    #[boxed_inner_target]
    pub Option<TestStruct1> struct_opt,
}

