// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <VbsEnclave\Enclave\Implementation\Trusted.h>
#include <VbsEnclave\Enclave\Abi\TypeMetadata.h>


namespace CodeGenTest
{
    namespace Abi::Runtime
    {
        static void EnforceMemoryRestriction()
        {
            if (ENABLE_ENCLAVE_RESTRICT_CONTAINING_PROCESS_ACCESS)
            {
                VbsEnclaveABI::Enclave::EnableEnclaveRestrictContainingProcessAccessOnce();
            }
        }
    }

    namespace Abi::Definitions
    {
        
        static inline void* FuncWithAllArgs_0_Generated_Stub(void* function_context)
        try
        {
            using AbiTypeT = CodeGenTest::Abi::Types::FuncWithAllArgs_0_args;
            using FlatBufferT = FlatbufferTypes::FuncWithAllArgs_0_argsT;
            Abi::Runtime::EnforceMemoryRestriction();
            HRESULT hr = VbsEnclaveABI::Enclave::CallVtl1ExportFromVtl1<AbiTypeT, FlatBufferT>(Trusted::Implementation::FuncWithAllArgs, function_context);
            LOG_IF_FAILED(hr);
            return ABI_HRESULT_TO_PVOID(hr);
        }
        catch (...)
        {
            HRESULT hr = wil::ResultFromCaughtException();
            LOG_IF_FAILED(hr);
            return ABI_HRESULT_TO_PVOID(hr);
        }

        void* __AbiRegisterVtl0Callbacks_CodeGenTest__(void* function_context)
        try
        {
            Abi::Runtime::EnforceMemoryRestriction();
            HRESULT hr = VbsEnclaveABI::Enclave::CallVtl1ExportFromVtl1<VbsEnclaveABI::Shared::Converters::AbiRegisterVtl0Callbacks_args, FlatbufferTypes::AbiRegisterVtl0Callbacks_argsT>(VbsEnclaveABI::Enclave::RegisterVtl0Callbacks, function_context);
            LOG_IF_FAILED(hr);
            return ABI_HRESULT_TO_PVOID(hr);
        }
        catch (...)
        {
            HRESULT hr = wil::ResultFromCaughtException();
            LOG_IF_FAILED(hr);
            return ABI_HRESULT_TO_PVOID(hr);
        }

    };
}
