// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#![allow(unused)]
#![allow(non_snake_case)]

use alloc::string::String;
use alloc::vec::Vec;
use crate::implementation::types::*;

pub trait Trusted {

    fn FuncWithAllArgs(arg1 : bool, arg2 : Option<&u32>, arg3 : Option<&mut i32>, arg4 : Option<&mut u64>, arg5 : &mut TestStruct1, arg6 : Option<&mut TestStruct2>, arg7 : &mut Vec<TestStruct2>, arg8 : &mut Vec<i16>, arg9 : &mut [widestring::U16String;2]) -> Result<i32, edlcodegen_enclave::AbiError>;

}
