// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#![allow(unused)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use alloc::string::String;
use alloc::vec::Vec;
use alloc::boxed::Box;
use crate::abi::fb_support::fb_types::code_gen_test::flatbuffer_types;
pub use crate::abi::abi_types::edl;
use edlcodegen_enclave::EdlDerive;

pub const VALUE1: u32 = 1;

#[repr(u32)]
#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_enum(flatbuffer_types::TestEnum)]
pub enum TestEnum {
    #[default]
    Value1 = 1,
}

#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(flatbuffer_types::TestStruct1T)]
pub struct TestStruct1 {
    pub int64_val: i64,
    pub uint64_val: u64,
    pub array1: [i64;5],
}

#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(flatbuffer_types::TestStruct2T)]
pub struct TestStruct2 {
    pub int32_opt: Option<i32>,

    #[boxed_target]
    pub struct_no_opt: TestStruct1,

    #[boxed_inner_target]
    pub struct_opt: Option<TestStruct1>,
}

