// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <VbsEnclave\Enclave\AbiDefinitions.h>

// Explicitly add linker statements so the generated export functions created by the code generator 
// can be exported when used to create a static lib.
#pragma comment(linker, "/include:FuncWithAllArgs_0_Generated_Stub")
#pragma comment(linker, "/include:__AbiRegisterVtl0Callbacks_CodeGenTest__")

extern "C" __declspec(dllexport) void* FuncWithAllArgs_0_Generated_Stub(void* function_context) 
{
    return CodeGenTest::AbiDefinitions::FuncWithAllArgs_0_Generated_Stub(function_context);
}

extern "C" __declspec(dllexport) void* __AbiRegisterVtl0Callbacks_CodeGenTest__(void* function_context) 
{
    return CodeGenTest::AbiDefinitions::__AbiRegisterVtl0Callbacks_CodeGenTest__(function_context);
}

