// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <VbsEnclaveABI\Shared\VbsEnclaveAbiBase.h>

namespace CodeGenTest::Types
{
    struct TestStruct1;
    struct TestStruct2;

    enum : std::uint32_t
    {
        Value1 = 1,
    };

    enum class TestEnum : std::uint32_t
    {
        Value1 = 1,
    };

    struct TestStruct1
    {
        std::int64_t int64_val {};
        std::uint64_t uint64_val {};
        std::array<std::int64_t, 5> array1 {};
    };

    struct TestStruct2
    {
        std::unique_ptr<int32_t> int32_ptr {};
        TestStruct1 struct_no_ptr {};
        std::unique_ptr<TestStruct1> struct_ptr {};
    };

}

