// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#![allow(unused)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use alloc::string::String;
use alloc::vec::Vec;
use alloc::boxed::Box;
use crate::implementation::types::*;
use crate::abi::fb_support::fb_types::code_gen_test::flatbuffer_types;
use crate::abi::fb_support::fb_types::edl::WStringT;
use edlcodegen_enclave::EdlDerive;
use widestring::{U16String, U16Str};


#[repr(C)]
#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(flatbuffer_types::FuncWithAllArgs_0_ArgsT)]
pub struct FuncWithAllArgs_0_Args {
    pub m_arg1: bool,
    pub m_arg2: Option<u32>,
    pub m_arg3: Option<i32>,
    pub m_arg4: Option<u64>,

    #[boxed_target]
    pub m_arg5: TestStruct1,

    #[boxed_inner_target]
    pub m_arg6: Option<TestStruct2>,
    pub m_arg7: Vec<TestStruct2>,
    pub m_arg8: Vec<i16>,
    pub m_arg9: [U16String;2],
    pub m__return_value_: i32,
}

#[repr(C)]
#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(flatbuffer_types::FuncWithAllArgs_1_ArgsT)]
pub struct FuncWithAllArgs_1_Args {
    pub m_arg1: bool,
    pub m_arg2: Option<u32>,
    pub m_arg3: Option<i32>,
    pub m_arg4: Option<u64>,

    #[boxed_target]
    pub m_arg5: TestStruct1,

    #[boxed_inner_target]
    pub m_arg6: Option<TestStruct2>,
    pub m_arg7: Vec<TestStruct2>,
    pub m_arg8: Vec<i16>,
    pub m_arg9: [U16String;2],
    pub m__return_value_: i32,
}

#[derive(Debug, Clone, PartialEq, Default, EdlDerive)]
#[target_struct(flatbuffer_types::AbiRegisterVtl0Callbacks_argsT)]
pub struct AbiRegisterVtl0Callbacks_args
{
    pub m_callback_addresses: Vec<u64>,
    pub m_callback_names: Vec<String>,
    pub m__return_value_: i32,
}

impl core::convert::From<U16String> for WStringT {
    fn from(src: U16String) -> Self {
        Self { wchars: src.clone().into_vec() }
    }
}

impl core::convert::From<WStringT> for U16String {
    fn from(src: WStringT) -> Self {
        U16String::from_vec(src.wchars)
    }
}

impl core::convert::From<U16String> for Box<WStringT> {
    fn from(src: U16String) -> Self {
        Box::new(WStringT{ wchars: src.clone().into_vec() })
    }
}

impl core::convert::From<Box<WStringT>> for U16String {
    fn from(src: Box<WStringT>) -> Self {
        U16String::from_vec(src.wchars)
    }
}
