// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#![allow(unused)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[allow(
    mismatched_lifetime_syntaxes,
    unsafe_op_in_unsafe_fn,
    dead_code,
    unused_imports,
    clippy::extra_unused_lifetimes,
    clippy::derivable_impls,
    clippy::missing_safety_doc
)]
pub mod fb_types{
    use edlcodegen_enclave::FlatbufferPack;
    use edlcodegen_enclave::impl_flatbuffer_pack;
    use code_gen_test::flatbuffer_types::*;

    include!(concat!(env!("OUT_DIR"), "/flatbuffer_gen/mod.rs"));

    impl_flatbuffer_pack!(FuncWithAllArgs_0_ArgsT, FuncWithAllArgs_0_Args<'a>);
    impl_flatbuffer_pack!(FuncWithAllArgs_1_ArgsT, FuncWithAllArgs_1_Args<'a>);
    impl_flatbuffer_pack!(AbiRegisterVtl0Callbacks_argsT, AbiRegisterVtl0Callbacks_args<'a>);
}
