// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <wil/enclave/wil_for_enclaves.h>
#include <VbsEnclave\Enclave\Abi\Definitions.h>


extern "C" __declspec(dllexport) void* FuncWithAllArgs_0_Generated_Stub(void* function_context) 
{
    return CodeGenTest::Abi::Definitions::FuncWithAllArgs_0_Generated_Stub(function_context);
}

extern "C" __declspec(dllexport) void* __AbiRegisterVtl0Callbacks_CodeGenTest__(void* function_context) 
{
    return CodeGenTest::Abi::Definitions::__AbiRegisterVtl0Callbacks_CodeGenTest__(function_context);
}

