parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false
- name: OfficialBuild
  type: boolean
  default: true
- name: BuildTarget
  type: string
  default: 'CodeGen'
  values:
  - CodeGen
  - SDK

variables:
- template: variables/version.yml@self
- template: variables/OneBranchVariables.yml@self
  parameters:
    debug: ${{ parameters.debug }}

- ${{ if eq(parameters.BuildTarget, 'CodeGen') }}:
  - name: StageName
    value: 'Build_codegen'
  - name: VpackName
    value: 'VbsEnclaveTooling.EdlCodeGen'
  - name: VpackDescription
    value: 'VbsEnclave Code Generator'
  - name: VPackVersion
    value: '$(CodeGenBuildVersion)'
  - name : ArtifactName
    value: 'codegen_content'

- ${{ else }}:
  - name: StageName
    value: 'Build_veil_sdk'
  - name: VpackName
    value: 'VbsEnclaveTooling.SDK'
  - name: VpackDescription
    value: 'VbsEnclave SDK'
  - name: VPackVersion
    value: '$(SdkBuildVersion)'
  - name: ArtifactName
    value: 'sdk_content'

trigger: none

pool:
  type: windows

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
    
    - repository: Vcpkg
      type: github
      name: microsoft/vcpkg
      endpoint: microsoft
      ref: refs/heads/master
      trigger: none

extends:
  template: v2/Microsoft.Official.yml@templates
  parameters:
    platform:     
      name: 'windows_undocked'
    
    featureFlags:
      WindowsHostVersion:
        Version: 2022
            
    cloudvault:
      enabled: false
    
    globalSdl:
      isNativeCode: true
      asyncSdl:
        enabled: true
      tsa:
        enabled: true
      codeql:
        compiled: 
          enabled: true
        tsaEnabled: true
      
    stages:

      - ${{ if eq(parameters.BuildTarget, 'CodeGen') }}:
        - stage: Build
          displayName: 'Build CodeGenerator'
          jobs:
          - template: AzurePipelineTemplates/jobs/CodeGenBuildJob.yml@self
            parameters:
              CodeGenBuildVersion: $(CodeGenBuildVersion)
              OfficialBuild: ${{ parameters.OfficialBuild }}
              ArtifactName: $(ArtifactName)

      - ${{ if eq(parameters.BuildTarget, 'SDK') }}:
        - stage: Build
          displayName: 'Build SDK'
          jobs:
          - template: AzurePipelineTemplates/jobs/SdkBuildJob.yml@self
            parameters:
              SdkBuildVersion: $(SdkBuildVersion)
              OfficialBuild: ${{ parameters.OfficialBuild }}
              ArtifactName: $(ArtifactName)

      - stage: vpack
        dependsOn: Build
        displayName: 'Create vpack package'
        jobs:
        - job: Packaging
          pool:
            type: windows
          variables:
            ob_outputDirectory: '$(Build.SourcesDirectory)\out'
            ob_createvpack_enabled: true
            ob_createvpack_packagename: $(VpackName)
            ob_createvpack_owneralias: VbsEnclaveTooling
            ob_createvpack_description: $(VpackDescription)
            ob_createvpack_provData: true
            ob_createvpack_versionAs: string
            ob_createvpack_version: $(VPackVersion)

          steps:
            - task: DownloadPipelineArtifact@2
              displayName: 'Download artifacts'
              inputs:
                artifactName: $(ArtifactName)
                targetPath: $(ob_outputDirectory)

