// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <VbsEnclave\Enclave\Implementation\Types.h>
#include <VbsEnclave\Enclave\Abi\FlatbufferTypes.h>

namespace CodeGenTest::Abi::Types
{
    using namespace CodeGenTest::Types;

    struct FuncWithAllArgs_0_args
    {
        bool m_arg1 {};
        std::optional<std::uint32_t> m_arg2 {};
        std::optional<std::int32_t> m_arg3 {};
        std::optional<std::uint64_t> m_arg4 {};
        TestStruct1 m_arg5 {};
        std::optional<TestStruct2> m_arg6 {};
        std::vector<TestStruct2> m_arg7 {};
        std::vector<std::int16_t> m_arg8 {};
        std::array<std::wstring, 2> m_arg9 {};
        HRESULT m__return_value_ {};
    };

    struct FuncWithAllArgs_1_args
    {
        bool m_arg1 {};
        std::optional<std::uint32_t> m_arg2 {};
        std::optional<std::int32_t> m_arg3 {};
        std::optional<std::uint64_t> m_arg4 {};
        TestStruct1 m_arg5 {};
        std::optional<TestStruct2> m_arg6 {};
        std::vector<TestStruct2> m_arg7 {};
        std::vector<std::int16_t> m_arg8 {};
        std::array<std::wstring, 2> m_arg9 {};
        HRESULT m__return_value_ {};
    };

}
