// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.


// This file should be included in the developer's enclave project to ensure
// the enclave export symbols are properly exposed by the enclave DLL.
#pragma comment(linker, "/include:FuncWithAllArgs_0_Generated_Stub")
#pragma comment(linker, "/include:__AbiRegisterVtl0Callbacks_CodeGenTest__")

