# build file for the CodeGenerator soliution using the x64 and arm64 platforms
parameters:
  - name: CodeGenBuildVersion
    type: string
  - name: OfficialBuild
    type: boolean
    default: false
  - name: ArtifactName
    type: string

jobs:
- job: build_artifacts
  displayName: 'CodeGen'
  pool:
    type: windows
  strategy:
    matrix:
      x64_Release:
        Platform: x64
        Configuration: Release
      x64_Debug:
        Platform: x64
        Configuration: Debug
      arm64_Release:
        Platform: ARM64
        Configuration: Release
      arm64_Debug:
        Platform: ARM64
        Configuration: Debug
  variables:
    CodeGenSolution: $(Build.SourcesDirectory)\VbsEnclaveTooling.sln
    VcpkgDirectory: $(Build.SourcesDirectory)\src\ToolingSharedLibrary\vcpkg_installed\x64-windows-static-cfg
    VcpkgToolsDirectory: $(VcpkgDirectory)\x64-windows-static-cfg\tools
    VcpkgSourcesDirectory: $(VcpkgDirectory)\x64-windows-static-cfg
    VCPKG_ROOT: '$(Pipeline.Workspace)\s\vcpkg'
    VCPKG_DEFAULT_TRIPLET: 'x64-windows'
    ob_outputDirectory: $(Build.SourcesDirectory)\out
    ob_artifactBaseName: $(ArtifactName)-build-$(Platform)-$(Configuration)
    BaseBuildDirectory: $(Build.SourcesDirectory)\_build
    IsOfficialBuild: ${{ parameters.OfficialBuild }}

    # vpack details
    ${{ if eq(parameters.OfficialBuild, 'false') }}:
      ob_sdl_codeSignValidation_excludes: '-|**\*.exe;-|**\*.dll' 

    ob_sdl_prefast_enabled: true
    ob_sdl_checkCompliantCompilerWarnings: true
    ob_symbolsPublishing_enabled: ${{ parameters.OfficialBuild }}
    ob_symbolsPublishing_symbolsFolder: '$(ob_outputDirectory)'
    ob_symbolsPublishing_searchPattern: '**\*.pdb'
    ob_symbolsPublishing_indexSources: true

  steps:
    - checkout: Vcpkg
      path: 's\vcpkg'
      displayName: "Checkout Vcpkg"
    - script: |
        cd $(VCPKG_ROOT)
        .\bootstrap-vcpkg.bat
      displayName: "Bootstrap vcpkg"
    - script: |
        cd $(VCPKG_ROOT)
        .\vcpkg.exe integrate install
      displayName: "Integrate vcpkg into msbuild"

    - task: NuGetCommand@2
      displayName: NuGet restore VbsEnclaveTooling.sln
      inputs:
        command: 'restore'
        restoreSolution: '$(CodeGenSolution)'
        feedsToUse: config
        nugetConfigPath: NuGet.config

    - task: VSBuild@1
      displayName: 'EdlCodeGen $(Platform) $(Configuration)'
      inputs:
        solution: $(CodeGenSolution)
        msbuildArgs: /p:VbsEnclaveCodegenVersion=${{ parameters.CodeGenBuildVersion }}
        platform:  $(Platform)
        configuration: $(Configuration)

    # Copy veil_enclave_cpp_support.lib artifacts
    - task: CopyFiles@2
      displayName: Copy lib artifacts
      inputs:
        SourceFolder: $(BaseBuildDirectory)
        Contents: |
          **\veil_*.pdb
          **\veil_*.lib
        TargetFolder: $(ob_outputDirectory)/$(Platform)/$(Configuration)
        flattenFolders: true

    # We only need one copy of the EdlCodeGen and flatc executables, and source files, so we will
    # sign and copy them only from the x64 Release build only.

    # Sign binaries in build folder
    - task: onebranch.pipeline.signing@1
      displayName: '🔒 Onebranch Signing for edlcodegen executable'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'), eq(variables['IsOfficialBuild'], 'true'))
      inputs:
        command: sign
        signing_profile: external_distribution
        files_to_sign: '**/*.dll;**/*.exe'
        search_root: $(BaseBuildDirectory)

    # Sign vcpkg binaries
    - task: onebranch.pipeline.signing@1
      displayName: '🔒 Onebranch Signing for flatc executable'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'), eq(variables['IsOfficialBuild'], 'true'))
      inputs:
        command: sign 
        signing_profile: 135020002 # OSS Third party cert
        files_to_sign: '**/*.dll;**/*.exe' 
        search_root: $(VcpkgToolsDirectory)

    # Copy edlcodegen
    - task: CopyFiles@2
      displayName: 'Copy edlcodegen'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(BaseBuildDirectory)/x64/Release'
        Contents: |
          edlcodegen.exe
          edlcodegen.pdb
        TargetFolder: '$(ob_outputDirectory)/bin'

    # Copy vcpkg folders/
    - task: CopyFiles@2
      displayName: 'Copy vcpkg folder'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(VcpkgSourcesDirectory)'
        Contents: '**/*'
        TargetFolder: '$(ob_outputDirectory)/vcpkg'

    # Copy flatc pdb folders/
    - task: CopyFiles@2
      displayName: 'Copy flac pdb to vcpkg folder'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(VCPKG_ROOT)\buildtrees\flatbuffers\x64-windows-static-cfg-rel'
        Contents: '**/flatc.pdb'
        TargetFolder: '$(ob_outputDirectory)/vcpkg/tools/flatbuffers'
    
    # Copy VbsEnclaveABI/
    - task: CopyFiles@2
      displayName: 'Copy VbsEnclaveABI folder'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/src/ToolingSharedLibrary/Includes'
        Contents: 'VbsEnclaveABI/**'
        TargetFolder: '$(ob_outputDirectory)/src'

    # Copy wil for enclaves headers
    - task: CopyFiles@2
      displayName: 'Copy wil folder'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/Common/veil_enclave_wil_inc'
        Contents: 'wil/**'
        TargetFolder: '$(ob_outputDirectory)/src'
