# build file for the veil soliution using the x64 and arm64 platforms
parameters:
  - name: OfficialBuild
    type: boolean
    default: false
  - name: ArtifactName
    type: string
  - name: UsNativeCompiler
    type: boolean
    default: false

jobs:
- job: build_artifacts
  displayName: 'SDK'
  pool:
    type: windows
  strategy:
    matrix:
      x64_Release:
        Platform: x64
        Configuration: Release
      x64_Debug:
        Platform: x64
        Configuration: Debug
      arm64_Release:
        Platform: arm64
        Configuration: Release
      arm64_Debug:
        Platform: arm64
        Configuration: Debug
  variables:
    SdkSolution: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\vbs_enclave_implementation_library.sln
    SdkBuildDirectory: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\_build
    SdkSourceDirectory: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\src
    ob_outputDirectory: $(Build.SourcesDirectory)\out
    ob_artifactBaseName: $(ArtifactName)-build-$(Platform)-$(Configuration)

    # vpack details
    ${{ if eq(parameters.OfficialBuild, 'false') }}:
      ob_sdl_codeSignValidation_excludes: '-|**\*.exe;-|**\*.dll' 

    ob_sdl_prefast_enabled: true
    ob_sdl_checkCompliantCompilerWarnings: true
    ob_symbolsPublishing_enabled: ${{ parameters.OfficialBuild }}
    ob_symbolsPublishing_symbolsFolder: '$(ob_outputDirectory)'
    ob_symbolsPublishing_searchPattern: '**\*.pdb'
    ob_symbolsPublishing_indexSources: true
    
    # Use Windows native compiler for static libs when building the sdk vpack so they can be consumed
    # by projects in the OS.
    ob_NativeCompiler_enabled: ${{ parameters.UsNativeCompiler }}
    ob_NativeCompiler_TaskVerbosity: 'Detailed'
    ob_NativeCompiler_UseOSBranchVersion: true
    ob_NativeCompiler_TargetOsBranch: 'official/ge_current'
    ob_NativeCompiler_UcrtPlatform: $(Platform)
    ob_NativeCompiler_SolutionDirectory: '$(Build.SourcesDirectory)\src\VbsEnclaveSDK'
  steps:
    - task: NuGetCommand@2
      displayName: Veil NuGet restore
      inputs:
        command: 'restore'
        restoreSolution: '$(SdkSolution)'
        feedsToUse: config
        nugetConfigPath: NuGet.config

    - task: VSBuild@1
      displayName: 'Veil $(Platform) $(Configuration)'
      inputs:
        solution: $(SdkSolution)
        msbuildArgs: /p:WindowsNativeCompilerEnabled=$(ob_NativeCompiler_enabled)
        platform:  $(Platform)
        configuration: $(Configuration)
  
    # Sign binaries in build folder
    - task: onebranch.pipeline.signing@1
      displayName: '🔒 Onebranch Signing for host dlls'
      condition: eq(${{ parameters.OfficialBuild }}, 'true')
      inputs:
        command: sign
        signing_profile: external_distribution
        files_to_sign: '**/*.dll;**/*.exe'
        search_root: $(SdkBuildDirectory)

    - task: CopyFiles@2
      displayName: Copy artifacts
      inputs:
        SourceFolder: $(SdkBuildDirectory)
        Contents: |
          **\veil_*.pdb
          **\veil_*.lib
          **\veil_*.dll
        TargetFolder: $(ob_outputDirectory)/$(Platform)/$(Configuration)
        flattenFolders: true

    # We only need one copy of the source files, so we will
    # copy them only during the x64 Release build.

    # Copy veil_enclave_lib header files
    - task: CopyFiles@2
      displayName: 'Copy veil_enclave_lib header files'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(SdkSourceDirectory)/veil_enclave_lib'
        TargetFolder: '$(ob_outputDirectory)/src/veil/enclave'
        Contents: |
          **/*.h
          !Generated Files/**

    # Native compiler builds require /export (not /include) directives to correctly
    # export enclave SDK functions from DLLs built with razzle sources files.
    - task: PowerShell@2
      displayName: 'Replace include linker statements with export statements'
      condition: eq(variables['ob_NativeCompiler_enabled'], 'true')
      inputs:
        targetType: 'inline'
        script: |
          $file = "$(SdkSourceDirectory)/veil_enclave_lib/Generated Files/VbsEnclave/Enclave/Abi/LinkerPragmas.veil_abi.cpp"
          $content = Get-Content -Path $file -Raw
          $updated = $content -replace '"/include:', '"/export:'
          Set-Content -Path $file -Value $updated -Encoding UTF8

    # Copy ABI linker pragmas file only once.
    - task: CopyFiles@2
      displayName: 'Copy VbsEnclave SDK linker pragmas file'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(SdkSourceDirectory)/veil_enclave_lib/Generated Files/VbsEnclave/Enclave/Abi'
        TargetFolder: '$(ob_outputDirectory)/exports'
        Contents: |
          LinkerPragmas.veil_abi.cpp
        flattenFolders: true

    # Copy veil_enclave_cpp_support_lib header files
    - task: CopyFiles@2
      displayName: 'Copy veil_host_lib header files'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(SdkSourceDirectory)/veil_host_lib'
        TargetFolder: '$(ob_outputDirectory)/src/veil/host'
        Contents: |
          **/*.h
          !Generated Files/**

    # Copy veil_any_inc header files
    - task: CopyFiles@2
      displayName: 'Copy veil_any_inc header files'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(SdkSourceDirectory)/veil_any_inc'
        TargetFolder: '$(ob_outputDirectory)/src/veil/veil_any_inc'
        Contents: |
          **/*.h

    # Copy wil for enclaves headers
    - task: CopyFiles@2
      displayName: 'Copy wil folder'
      condition: and(eq(variables['Platform'], 'x64'), eq(variables['Configuration'], 'Release'))
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/Common/veil_enclave_wil_inc'
        Contents: 'wil/**'
        TargetFolder: '$(ob_outputDirectory)/src'
