# build file for the veil soliution using the x64 and arm64 platforms
parameters:
  - name: SdkBuildVersion
    type: string
  - name: OfficialBuild
    type: boolean
    default: false
  - name: ArtifactName
    type: string

jobs:
- job: Build_and_package_sdk
  displayName: 'Build veil solution and SDK nuget package'
  pool:
    type: windows
  variables:
    SdkSolution: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\vbs_enclave_implementation_library.sln
    SdkSourceDirectory: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\src
    VeilHostVcxProj: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\src\veil_host_lib\veil_host_lib.vcxproj
    VeilHostPackageConfig: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\src\veil_host_lib\packages.config
    VeilEnclaveVcxProj: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\src\veil_enclave_lib\veil_enclave_lib.vcxproj
    VeilEnclavePackageConfig: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\src\veil_enclave_lib\packages.config
    ob_outputDirectory: $(Build.SourcesDirectory)\sdk
    ob_artifactBaseName: $(ArtifactName) 
    SdkNugetPackageVersion: ${{ parameters.SdkBuildVersion }}
    BaseBuildDirectory: $(Build.SourcesDirectory)\_build
    SdkBuildDirectory: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\_build
    x64ReleaseBuildLocation: $(SdkBuildDirectory)\x64\Release
    x64DebugBuildLocation: $(SdkBuildDirectory)\x64\Debug
    Arm64ReleaseBuildLocation: $(SdkBuildDirectory)\ARM64\Release
    Arm64DebugBuildLocation: $(SdkBuildDirectory)\ARM64\Debug

    # veil_enclave_lib pack args
    VeilEnclaveLibX64Release: vbsenclave_sdk_enclave_x64_Release_lib=$(x64ReleaseBuildLocation)\veil_enclave_x64_Release_lib.lib  
    VeilEnclaveLibX64Debug: vbsenclave_sdk_enclave_x64_Debug_lib=$(x64DebugBuildLocation)\veil_enclave_x64_Debug_lib.lib
    VeilEnclaveLibARM64Release: vbsenclave_sdk_enclave_ARM64_Release_lib=$(Arm64ReleaseBuildLocation)\veil_enclave_ARM64_Release_lib.lib
    VeilEnclaveLibARM64Debug: vbsenclave_sdk_enclave_ARM64_Debug_lib=$(Arm64DebugBuildLocation)\veil_enclave_ARM64_Debug_lib.lib
    VeilEnclavePdbX64Release: vbsenclave_sdk_enclave_x64_Release_pdb=$(x64ReleaseBuildLocation)\veil_enclave_x64_Release_lib.pdb  
    VeilEnclavePdbX64Debug: vbsenclave_sdk_enclave_x64_Debug_pdb=$(x64DebugBuildLocation)\veil_enclave_x64_Debug_lib.pdb
    VeilEnclavePdbARM64Release: vbsenclave_sdk_enclave_ARM64_Release_pdb=$(Arm64ReleaseBuildLocation)\veil_enclave_ARM64_Release_lib.pdb
    VeilEnclavePdbARM64Debug: vbsenclave_sdk_enclave_ARM64_Debug_pdb=$(Arm64DebugBuildLocation)\veil_enclave_ARM64_Debug_lib.pdb
    
    # veil_host_lib pack args
    VeilHostLibX64Release: vbsenclave_sdk_host_x64_Release_lib=$(x64ReleaseBuildLocation)\veil_host_lib\veil_host_x64_Release_lib.lib  
    VeilHostLibX64Debug: vbsenclave_sdk_host_x64_Debug_lib=$(x64DebugBuildLocation)\veil_host_lib\veil_host_x64_Debug_lib.lib
    VeilHostLibARM64Release: vbsenclave_sdk_host_ARM64_Release_lib=$(Arm64ReleaseBuildLocation)\veil_host_lib\veil_host_ARM64_Release_lib.lib
    VeilHostLibARM64Debug: vbsenclave_sdk_host_ARM64_Debug_lib=$(Arm64DebugBuildLocation)\veil_host_lib\veil_host_ARM64_Debug_lib.lib
    VeilHostPdbX64Release: vbsenclave_sdk_host_x64_Release_pdb=$(x64ReleaseBuildLocation)\veil_host_lib\veil_host_x64_Release_lib.pdb  
    VeilHostPdbX64Debug: vbsenclave_sdk_host_x64_Debug_pdb=$(x64DebugBuildLocation)\veil_host_lib\veil_host_x64_Debug_lib.pdb
    VeilHostPdbARM64Release: vbsenclave_sdk_host_ARM64_Release_pdb=$(Arm64ReleaseBuildLocation)\veil_host_lib\veil_host_ARM64_Release_lib.pdb
    VeilHostPdbARM64Debug: vbsenclave_sdk_host_ARM64_Debug_pdb=$(Arm64DebugBuildLocation)\veil_host_lib\veil_host_ARM64_Debug_lib.pdb
    
    # veil_enclave_cpp_support_lib pack args
    VeilCppSupportLibX64Release: vbsenclave_sdk_cpp_support_x64_Release_lib=$(x64ReleaseBuildLocation)\veil_enclave_cpp_support_x64_Release_lib.lib  
    VeilCppSupportLibX64Debug: vbsenclave_sdk_cpp_support_x64_Debug_lib=$(x64DebugBuildLocation)\veil_enclave_cpp_support_x64_Debug_lib.lib
    VeilCppSupportLibARM64Release: vbsenclave_sdk_cpp_support_ARM64_Release_lib=$(Arm64ReleaseBuildLocation)\veil_enclave_cpp_support_ARM64_Release_lib.lib
    VeilCppSupportLibARM64Debug: vbsenclave_sdk_cpp_support_ARM64_Debug_lib=$(Arm64DebugBuildLocation)\veil_enclave_cpp_support_ARM64_Debug_lib.lib
    VeilCppSupportPdbX64Release: vbsenclave_sdk_cpp_support_x64_Release_pdb=$(x64ReleaseBuildLocation)\veil_enclave_cpp_support_x64_Release_lib.pdb  
    VeilCppSupportPdbX64Debug: vbsenclave_sdk_cpp_support_x64_Debug_pdb=$(x64DebugBuildLocation)\veil_enclave_cpp_support_x64_Debug_lib.pdb
    VeilCppSupportPdbARM64Release: vbsenclave_sdk_cpp_support_ARM64_Release_pdb=$(Arm64ReleaseBuildLocation)\veil_enclave_cpp_support_ARM64_Release_lib.pdb
    VeilCppSupportPdbARM64Debug: vbsenclave_sdk_cpp_support_ARM64_Debug_pdb=$(Arm64DebugBuildLocation)\veil_enclave_cpp_support_ARM64_Debug_lib.pdb

    # vpack details
    ${{ if eq(parameters.OfficialBuild, 'false') }}:
      ob_sdl_codeSignValidation_excludes: '-|**\*.exe;-|**\*.dll' 

    ob_sdl_prefast_enabled: true
    ob_sdl_checkCompliantCompilerWarnings: true
    ob_symbolsPublishing_enabled: ${{ parameters.OfficialBuild }}
    ob_symbolsPublishing_symbolsFolder: '$(ob_outputDirectory)'
    ob_symbolsPublishing_searchPattern: '**\*.pdb'
    ob_symbolsPublishing_indexSources: true
    
  steps:
    - task: NuGetCommand@2
      displayName: NuGet restore vbs_enclave_implementation_library.sln
      inputs:
        command: 'restore'
        restoreSolution: '$(SdkSolution)'
        feedsToUse: config
        nugetConfigPath: NuGet.config

    - task: VSBuild@1
      displayName: 'Build Veil Solution x64 release'
      inputs:
        solution: $(SdkSolution)
        platform:  'x64'
        configuration: 'Release'

    - task: VSBuild@1
      displayName: 'Build Veil Solution  arm64 release'
      inputs:
        solution: $(SdkSolution)
        platform:  'arm64'
        configuration: 'Release'

    - task: VSBuild@1
      displayName: 'Build Veil Solution x64 debug'
      inputs:
        solution: $(SdkSolution)
        platform:  'x64'
        configuration: 'Debug'

    - task: VSBuild@1
      displayName: 'Build Veil Solution  arm64 debug'
      inputs:
        solution: $(SdkSolution)
        platform:  'arm64'
        configuration: 'Debug'

    - task: NuGetToolInstaller@1
      displayName: Use NuGet 6.0.2
      continueOnError: True
      inputs:
        versionSpec: 6.0.2

    # Pack SDK nuget package
    - task: NuGetCommand@2
      displayName: 'Build SDK NuGet package'
      inputs:
        command: 'custom'
        arguments: 'pack src\VbsEnclaveSDK\src\veil_nuget\Nuget\Microsoft.Windows.VbsEnclave.SDK.nuspec -NonInteractive -OutputDirectory $(BaseBuildDirectory) -Properties target_version=$(SdkNugetPackageVersion);$(VeilEnclaveLibX64Release);$(VeilEnclaveLibX64Debug);$(VeilEnclaveLibARM64Release);$(VeilEnclaveLibARM64Debug);$(VeilHostLibX64Release);$(VeilHostLibX64Debug);$(VeilHostLibARM64Release);$(VeilHostLibARM64Debug);$(VeilCppSupportLibX64Release);$(VeilCppSupportLibX64Debug);$(VeilCppSupportLibARM64Release);$(VeilCppSupportLibARM64Debug);$(VeilEnclavePdbX64Release);$(VeilEnclavePdbX64Debug);$(VeilEnclavePdbARM64Release);$(VeilEnclavePdbARM64Debug);$(VeilHostPdbX64Release);$(VeilHostPdbX64Debug);$(VeilHostPdbARM64Release);$(VeilHostPdbARM64Debug);$(VeilCppSupportPdbX64Release);$(VeilCppSupportPdbX64Debug);$(VeilCppSupportPdbARM64Release);$(VeilCppSupportPdbARM64Debug); -Version $(SdkNugetPackageVersion) -Verbosity Detailed'

    # Sign sdk nuget package
    - task: onebranch.pipeline.signing@1
      displayName: '🔒 Onebranch signing for SDK NuGet package'
      condition: eq(${{ parameters.OfficialBuild }}, 'true')
      inputs:
        command: sign
        cp_code: 'CP-401405' # CP-code
        files_to_sign: 'Microsoft.Windows.VbsEnclave.*.nupkg'
        search_root: $(BaseBuildDirectory)

    # Copy artifacts to pipeline
    - task: CopyFiles@2
      displayName: Copy build artifacts
      inputs:
        SourceFolder: $(SdkBuildDirectory)
        Contents: |
          Microsoft.Windows.VbsEnclave.SDK.$(SdkNugetPackageVersion).nupkg
          **\veil_enclave_cpp_support_*_lib.lib
          **\veil_enclave_cpp_support_*_lib.pdb
          **\veil_enclave_*_lib.lib
          **\veil_enclave_*_lib.pdb
          **\veil_host_*_lib.lib
          **\veil_host_*_lib.pdb
        TargetFolder: $(ob_outputDirectory)/lib
        flattenFolders: true

    # Copy veil_enclave_lib header files
    - task: CopyFiles@2
      displayName: 'Copy veil_enclave_lib header files'
      inputs:
        SourceFolder: '$(SdkSourceDirectory)/veil_enclave_lib'
        TargetFolder: '$(ob_outputDirectory)/src/veil/enclave'
        Contents: |
          **/*.h
          !Generated Files/**
    
    # Copy ABI linker pragmas file
    - task: CopyFiles@2
      displayName: 'Copy VbsEnclave SDK linker pragmas file'
      inputs:
        SourceFolder: '$(SdkSourceDirectory)/veil_enclave_lib/Generated Files/VbsEnclave/Enclave/Abi'
        TargetFolder: '$(ob_outputDirectory)/exports'
        Contents: |
          LinkerPragmas.veil_abi.cpp

    # Copy veil_enclave_cpp_support_lib header files
    - task: CopyFiles@2
      displayName: 'Copy veil_host_lib header files'
      inputs:
        SourceFolder: '$(SdkSourceDirectory)/veil_host_lib'
        TargetFolder: '$(ob_outputDirectory)/src/veil/host'
        Contents: |
          **/*.h
          !Generated Files/**

    # Copy veil_any_inc header files
    - task: CopyFiles@2
      displayName: 'Copy veil_any_inc header files'
      inputs:
        SourceFolder: '$(SdkSourceDirectory)/veil_any_inc'
        TargetFolder: '$(ob_outputDirectory)/src/veil/veil_any_inc'
        Contents: |
          **/*.h

    # Copy wil for enclaves headers
    - task: CopyFiles@2
      displayName: 'Copy wil folder'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/Common/veil_enclave_wil_inc'
        Contents: 'wil/**'
        TargetFolder: '$(ob_outputDirectory)/src'
