# nuget package file for the veil solution using the x64 and arm64 platforms
parameters:
  - name: SdkBuildVersion
    type: string
  - name: OfficialBuild
    type: boolean
    default: false
  - name: ArtifactName
    type: string

jobs:
- job: package_nuget
  displayName: 'Package sdk nuget'
  pool:
    type: windows
  variables:
    ob_artifactBaseName: $(ArtifactName)-nuget
    SdkNugetPackageVersion: ${{ parameters.SdkBuildVersion }}
    ob_outputDirectory: $(Build.SourcesDirectory)\out
    StagingDirectory: $(Build.SourcesDirectory)\staging
    SdkSourceDirectory: $(Build.SourcesDirectory)\src\VbsEnclaveSDK\src

  steps:
    - task: NuGetToolInstaller@1
      displayName: Use NuGet 6.0.2
      continueOnError: True
      inputs:
        versionSpec: 6.0.2

    - task: DownloadPipelineArtifact@2
      displayName: Download x64 Release
      inputs:
        artifact: $(ArtifactName)-build-x64-Release
        path: $(StagingDirectory)/x64/Release

    - task: DownloadPipelineArtifact@2
      displayName: Download x64 Debug
      inputs:
        artifact: $(ArtifactName)-build-x64-Debug
        path: $(StagingDirectory)/x64/Debug

    - task: DownloadPipelineArtifact@2
      displayName: Download ARM64 Release
      inputs:
        artifact: $(ArtifactName)-build-ARM64-Release
        path: $(StagingDirectory)/ARM64/Release

    - task: DownloadPipelineArtifact@2
      displayName: Download ARM64 Debug
      inputs:
        artifact: $(ArtifactName)-build-ARM64-Debug
        path: $(StagingDirectory)/ARM64/Debug

    # Combine nuget props into a single semi-colon delimited string for use in nuget pack command
    - powershell: |
        $props = ""
        foreach ($platform in @('x64','ARM64')) {
          foreach ($config in @('Release','Debug')) {
            # Enclave lib
            $propName = "vbsenclave_sdk_enclave_${platform}_${config}_lib"
            $propValue = "$(StagingDirectory)\${platform}\${config}\lib\veil_enclave_${platform}_${config}_lib.lib"
            $props += "$propName=$propValue;"

            # Host lib
            $propName = "vbsenclave_sdk_host_${platform}_${config}_lib"
            $propValue = "$(StagingDirectory)\${platform}\${config}\lib\veil_host_${platform}_${config}_lib.lib"
            $props += "$propName=$propValue;"

            # Cpp support lib
            $propName = "vbsenclave_sdk_cpp_support_${platform}_${config}_lib"
            $propValue = "$(StagingDirectory)\${platform}\${config}\lib\veil_enclave_cpp_support_${platform}_${config}_lib.lib"
            $props += "$propName=$propValue;"
          }
        }
        Write-Host "##vso[task.setvariable variable=VeilLibProps]$props"
      displayName: 'Generate VeilLibProps variable'

    # Place linker pragmas file in expected sdk source directory for inclusion in nuget package
    - task: CopyFiles@2
      displayName: 'Copy VbsEnclave SDK linker pragmas file'
      inputs:
        SourceFolder: '$(StagingDirectory)/x64/release/exports'
        TargetFolder: '$(SdkSourceDirectory)/veil_enclave_lib/Generated Files/VbsEnclave/Enclave/Abi'
        Contents: |
          LinkerPragmas.veil_abi.cpp

    # Pack SDK nuget package
    - task: NuGetCommand@2
      displayName: 'Create SDK NuGet package'
      inputs:
        command: 'custom'
        arguments: >
          pack $(SdkSourceDirectory)/veil_nuget/Nuget/Microsoft.Windows.VbsEnclave.SDK.nuspec
          -NonInteractive
          -OutputDirectory $(ob_outputDirectory)
          -Properties "target_version=$(SdkBuildVersion);$(VeilLibProps);"
          -Version $(SdkNugetPackageVersion)
          -Verbosity detailed

    # Sign sdk nuget package
    - task: onebranch.pipeline.signing@1
      displayName: '🔒 Onebranch signing for SDK NuGet package'
      condition: eq(${{ parameters.OfficialBuild }}, 'true')
      inputs:
        command: sign
        cp_code: 'CP-401405' # CP-code
        files_to_sign: 'Microsoft.Windows.VbsEnclave.*.nupkg'
        search_root: $(ob_outputDirectory)
