// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <VbsEnclave\HostApp\Untrusted.h>

namespace CodeGenTest
{
    namespace AbiDefinitions
    {
        using namespace CodeGenTest::DeveloperTypes;
        
        static inline void* FuncWithAllArgs_1_Generated_Stub(void* function_context)
        try
        {
            using DevTypeT = FuncWithAllArgs_1_args;
            using FlatBufferT = FlatbuffersDevTypes::FuncWithAllArgs_1_argsT;
            
            HRESULT hr = VbsEnclaveABI::HostApp::CallVtl0CallbackImplFromVtl0<DevTypeT, FlatBufferT>(Untrusted::Implementation::FuncWithAllArgs, function_context);
            LOG_IF_FAILED(hr);
            return ABI_HRESULT_TO_PVOID(hr);
        }
        catch (...)
        {
            HRESULT hr = wil::ResultFromCaughtException();
            LOG_IF_FAILED(hr);
            return ABI_HRESULT_TO_PVOID(hr);
        }

    };
}
