// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <VbsEnclave\HostApp\Implementation\Untrusted.h>
#include <VbsEnclave\HostApp\Abi\TypeMetadata.h>


namespace CodeGenTest
{
    
    namespace Abi::Definitions
    {
        
        static inline void* FuncWithAllArgs_1_Generated_Stub(void* function_context)
        try
        {
            using AbiTypeT = CodeGenTest::Abi::Types::FuncWithAllArgs_1_args;
            using FlatBufferT = FlatbufferTypes::FuncWithAllArgs_1_argsT;
            
            HRESULT hr = VbsEnclaveABI::HostApp::CallVtl0CallbackImplFromVtl0<AbiTypeT, FlatBufferT>(Untrusted::Implementation::FuncWithAllArgs, function_context);
            LOG_IF_FAILED(hr);
            return ABI_HRESULT_TO_PVOID(hr);
        }
        catch (...)
        {
            HRESULT hr = wil::ResultFromCaughtException();
            LOG_IF_FAILED(hr);
            return ABI_HRESULT_TO_PVOID(hr);
        }

    };
}
