// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <VbsEnclave\HostApp\Abi\AbiTypes.h>
#include <VbsEnclaveABI\Shared\ConversionHelpers.h>

namespace VbsEnclaveABI::Shared::Converters
{
    template <>
    struct StructMetadata<CodeGenTest::Types::TestStruct1>
    {
        static constexpr auto members = std::make_tuple(&CodeGenTest::Types::TestStruct1::int64_val,&CodeGenTest::Types::TestStruct1::uint64_val,&CodeGenTest::Types::TestStruct1::array1);
    };

    template <>
    struct StructMetadata<CodeGenTest::FlatbufferTypes::TestStruct1T>
    {
        static constexpr auto members = std::make_tuple(&CodeGenTest::FlatbufferTypes::TestStruct1T::int64_val,&CodeGenTest::FlatbufferTypes::TestStruct1T::uint64_val,&CodeGenTest::FlatbufferTypes::TestStruct1T::array1);
    };

    template <>
    struct StructMetadata<CodeGenTest::Types::TestStruct2>
    {
        static constexpr auto members = std::make_tuple(&CodeGenTest::Types::TestStruct2::int32_ptr,&CodeGenTest::Types::TestStruct2::struct_no_ptr,&CodeGenTest::Types::TestStruct2::struct_ptr);
    };

    template <>
    struct StructMetadata<CodeGenTest::FlatbufferTypes::TestStruct2T>
    {
        static constexpr auto members = std::make_tuple(&CodeGenTest::FlatbufferTypes::TestStruct2T::int32_ptr,&CodeGenTest::FlatbufferTypes::TestStruct2T::struct_no_ptr,&CodeGenTest::FlatbufferTypes::TestStruct2T::struct_ptr);
    };

    template <>
    struct StructMetadata<CodeGenTest::Abi::Types::FuncWithAllArgs_0_args>
    {
        static constexpr auto members = std::make_tuple(&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m_arg1,&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m_arg2,&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m_arg3,&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m_arg4,&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m_arg5,&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m_arg6,&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m_arg7,&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m_arg8,&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m_arg9,&CodeGenTest::Abi::Types::FuncWithAllArgs_0_args::m__return_value_);
    };

    template <>
    struct StructMetadata<CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT>
    {
        static constexpr auto members = std::make_tuple(&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m_arg1,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m_arg2,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m_arg3,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m_arg4,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m_arg5,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m_arg6,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m_arg7,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m_arg8,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m_arg9,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_0_argsT::m__return_value_);
    };

    template <>
    struct StructMetadata<CodeGenTest::Abi::Types::FuncWithAllArgs_1_args>
    {
        static constexpr auto members = std::make_tuple(&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m_arg1,&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m_arg2,&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m_arg3,&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m_arg4,&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m_arg5,&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m_arg6,&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m_arg7,&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m_arg8,&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m_arg9,&CodeGenTest::Abi::Types::FuncWithAllArgs_1_args::m__return_value_);
    };

    template <>
    struct StructMetadata<CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT>
    {
        static constexpr auto members = std::make_tuple(&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m_arg1,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m_arg2,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m_arg3,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m_arg4,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m_arg5,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m_arg6,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m_arg7,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m_arg8,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m_arg9,&CodeGenTest::FlatbufferTypes::FuncWithAllArgs_1_argsT::m__return_value_);
    };

    template <>
    struct StructMetadata<CodeGenTest::FlatbufferTypes::AbiRegisterVtl0Callbacks_argsT>
    {
        using CallbackArgs = CodeGenTest::FlatbufferTypes::AbiRegisterVtl0Callbacks_argsT;
        static constexpr auto members = std::make_tuple(&CallbackArgs::m_callback_addresses, &CallbackArgs::m_callback_names, &CallbackArgs::m__return_value_);
    };

}
