// This file was auto-generated by VbsEnclaveTooling.exe
// Changes to this file may be lost if the file is regenerated.

#include "VbsEnclaveBase.h"
namespace VbsEnclave
{

enum
{
    value1 = 10,
    value2 = 50,
};

#pragma pack(push, 1)
struct TestStruct
{
    size_t size;
    char* arg1;
    std::array<std::uint32_t, 5> arg2;
    std::array<std::uint32_t, 0x14> arg3;
    std::array<std::array<std::uint32_t, value1>, 10> arg4;
};
#pragma pack(pop)

enum TestEnum
{
    test_val1 = 0x01,
    test_val2 = 0x2,
    test_val3 = 0x3,
};
};
