// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#![no_std]
#![allow(clippy::all)]

extern crate alloc;

pub mod abi;
pub mod implementation;
pub mod stubs;
pub use edlcodegen_enclave::enclave_ffi::enable_enclave_restrict_containing_process_access_once;
pub use edlcodegen_enclave::{AbiError, return_hr_as_pvoid};
pub use edlcodegen_enclave::enclave_helpers::{
    call_vtl1_export_from_vtl1, register_vtl0_callouts
};
